/* LinguaDrive vocabulary bank — English topic packs (loaded by the app and by Node tests) */
(function (root) {
  'use strict';
  var BANK = {
    lang: 'en',
    topics: [
      { id: 'food', he: 'אוכל ושתייה', icon: '🍎', words: [
        { en: 'bread', he: 'לחם', t: 'בְּרֶד', ex: 'I buy fresh bread every morning.', exHe: 'אני קונה לחם טרי כל בוקר.' },
        { en: 'milk', he: 'חלב', t: 'מִילְק', ex: 'The milk is in the fridge.', exHe: 'החלב נמצא במקרר.' },
        { en: 'cheese', he: 'גבינה', t: "צִ'יז", ex: 'This cheese is from France.', exHe: 'הגבינה הזאת מצרפת.' },
        { en: 'egg', he: 'ביצה', t: 'אֶג', ex: 'I want one egg for breakfast.', exHe: 'אני רוצה ביצה אחת לארוחת בוקר.' },
        { en: 'apple', he: 'תפוח', t: 'אֶפֶּל', ex: 'She eats an apple every day.', exHe: 'היא אוכלת תפוח כל יום.' },
        { en: 'rice', he: 'אורז', t: 'רַייס', ex: 'We cook rice with vegetables.', exHe: 'אנחנו מבשלים אורז עם ירקות.' },
        { en: 'meat', he: 'בשר', t: 'מִיט', ex: 'He does not eat meat.', exHe: 'הוא לא אוכל בשר.' },
        { en: 'soup', he: 'מרק', t: 'סוּפּ', ex: 'The soup is too hot.', exHe: 'המרק חם מדי.' },
        { en: 'cake', he: 'עוגה', t: 'קֵייק', ex: 'My mother makes a great cake.', exHe: 'אמא שלי מכינה עוגה נהדרת.' },
        { en: 'juice', he: 'מיץ', t: "ג'וּס", ex: 'Orange juice is my favorite.', exHe: 'מיץ תפוזים הוא האהוב עליי.' },
        { en: 'coffee', he: 'קפה', t: 'קוֹפִי', ex: 'I drink coffee in the morning.', exHe: 'אני שותה קפה בבוקר.' },
        { en: 'tea', he: 'תה', t: 'טִי', ex: 'Do you want tea with lemon?', exHe: 'אתה רוצה תה עם לימון?' },
        { en: 'butter', he: 'חמאה', t: 'בַּאטֶר', ex: 'Put some butter on the bread.', exHe: 'שים קצת חמאה על הלחם.' },
        { en: 'sugar', he: 'סוכר', t: 'שוּגֶר', ex: 'No sugar in my coffee, thanks.', exHe: 'בלי סוכר בקפה שלי, תודה.' },
        { en: 'fruit', he: 'פרי', t: 'פְרוּט', ex: 'Fresh fruit is good for you.', exHe: 'פרי טרי טוב בשבילך.' },
        { en: 'vegetables', he: 'ירקות', t: "וֶג'טֶבֶּלְס", ex: 'We buy vegetables at the market.', exHe: 'אנחנו קונים ירקות בשוק.' },
        { en: 'breakfast', he: 'ארוחת בוקר', t: 'בְּרֶקְפֶסְט', ex: 'Breakfast is ready at eight.', exHe: 'ארוחת הבוקר מוכנה בשמונה.' },
        { en: 'lunch', he: 'ארוחת צהריים', t: "לַאנְץ'", ex: 'Let us have lunch together.', exHe: 'בוא נאכל ארוחת צהריים יחד.' },
        { en: 'dinner', he: 'ארוחת ערב', t: 'דִינֶר', ex: 'Dinner is at seven tonight.', exHe: 'ארוחת הערב בשבע הערב.' },
        { en: 'tasty', he: 'טעים', t: 'טֵייסְטִי', ex: 'This soup is really tasty.', exHe: 'המרק הזה ממש טעים.' }
      ] },
      { id: 'family', he: 'משפחה', icon: '👨‍👩‍👧', words: [
        { en: 'mother', he: 'אמא', t: 'מַאדֶר', ex: 'My mother lives in Haifa.', exHe: 'אמא שלי גרה בחיפה.' },
        { en: 'father', he: 'אבא', t: 'פַאדֶר', ex: 'His father is a teacher.', exHe: 'אבא שלו מורה.' },
        { en: 'parents', he: 'הורים', t: 'פֶּרֶנְטְס', ex: 'My parents visit us on Friday.', exHe: 'ההורים שלי מבקרים אותנו ביום שישי.' },
        { en: 'brother', he: 'אח', t: 'בְּרַאדֶר', ex: 'My brother is older than me.', exHe: 'אח שלי מבוגר ממני.' },
        { en: 'sister', he: 'אחות', t: 'סִיסְטֶר', ex: 'Her sister lives in London.', exHe: 'אחותה גרה בלונדון.' },
        { en: 'son', he: 'בן', t: 'סַאן', ex: 'Their son is ten years old.', exHe: 'הבן שלהם בן עשר.' },
        { en: 'daughter', he: 'בת', t: 'דוֹטֶר', ex: 'Our daughter studies medicine.', exHe: 'הבת שלנו לומדת רפואה.' },
        { en: 'husband', he: 'בעל', t: 'הַאסְבֶּנְד', ex: 'Her husband cooks very well.', exHe: 'בעלה מבשל טוב מאוד.' },
        { en: 'wife', he: 'אישה (רעיה)', t: 'וַוייף', ex: 'My wife speaks three languages.', exHe: 'אשתי מדברת שלוש שפות.' },
        { en: 'grandmother', he: 'סבתא', t: 'גְרֶנְדְמַאדֶר', ex: 'Grandmother tells wonderful stories.', exHe: 'סבתא מספרת סיפורים נפלאים.' },
        { en: 'grandfather', he: 'סבא', t: 'גְרֶנְדְפַאדֶר', ex: 'My grandfather is ninety years old.', exHe: 'סבא שלי בן תשעים.' },
        { en: 'baby', he: 'תינוק', t: 'בֵּייבִּי', ex: 'The baby sleeps all day.', exHe: 'התינוק ישן כל היום.' },
        { en: 'child', he: 'ילד', t: "צַ'יילְד", ex: 'Every child needs love.', exHe: 'כל ילד צריך אהבה.' },
        { en: 'children', he: 'ילדים', t: "צִ'ילְדְרֶן", ex: 'The children play in the garden.', exHe: 'הילדים משחקים בגינה.' },
        { en: 'uncle', he: 'דוד (קרוב משפחה)', t: 'אַנְקֶל', ex: 'My uncle has a big farm.', exHe: 'לדוד שלי יש חווה גדולה.' },
        { en: 'aunt', he: 'דודה', t: 'אַנְט', ex: 'Aunt Sara brings us presents.', exHe: 'דודה שרה מביאה לנו מתנות.' },
        { en: 'cousin', he: 'בן דוד', t: 'קַאזֶן', ex: 'My cousin works in Tel Aviv.', exHe: 'בן הדוד שלי עובד בתל אביב.' },
        { en: 'married', he: 'נשוי', t: 'מֶרִיד', ex: 'They are married with two kids.', exHe: 'הם נשואים עם שני ילדים.' },
        { en: 'together', he: 'יחד', t: 'טוּגֶדֶר', ex: 'We have dinner together on Friday.', exHe: 'אנחנו אוכלים ארוחת ערב יחד ביום שישי.' },
        { en: 'love', he: 'אהבה', t: 'לַאב', ex: 'I love my big family.', exHe: 'אני אוהב את המשפחה הגדולה שלי.' }
      ] },
      { id: 'work', he: 'עבודה ומשרד', icon: '💼', words: [
        { en: 'job', he: 'עבודה (משרה)', t: "ג'וֹבּ", ex: 'She found a new job.', exHe: 'היא מצאה עבודה חדשה.' },
        { en: 'office', he: 'משרד', t: 'אוֹפִיס', ex: 'The office opens at nine.', exHe: 'המשרד נפתח בתשע.' },
        { en: 'boss', he: 'בוס (מנהל)', t: 'בּוֹס', ex: 'My boss is very nice.', exHe: 'הבוס שלי נחמד מאוד.' },
        { en: 'meeting', he: 'פגישה', t: 'מִיטִינְג', ex: 'The meeting starts in ten minutes.', exHe: 'הפגישה מתחילה בעוד עשר דקות.' },
        { en: 'colleague', he: 'עמית לעבודה', t: 'קוֹלִיג', ex: 'My colleague helps me a lot.', exHe: 'העמית שלי עוזר לי מאוד.' },
        { en: 'salary', he: 'משכורת', t: 'סֶלֶרִי', ex: 'The salary is paid every month.', exHe: 'המשכורת משולמת כל חודש.' },
        { en: 'email', he: 'אימייל', t: 'אִימֵייל', ex: 'I read your email this morning.', exHe: 'קראתי את האימייל שלך הבוקר.' },
        { en: 'project', he: 'פרויקט', t: "פְּרוֹגֶ'קְט", ex: 'This project ends next month.', exHe: 'הפרויקט הזה מסתיים בחודש הבא.' },
        { en: 'task', he: 'משימה', t: 'טַאסְק', ex: 'This task is easy for me.', exHe: 'המשימה הזאת קלה בשבילי.' },
        { en: 'deadline', he: 'מועד אחרון', t: 'דֶדְלַיין', ex: 'The deadline is on Thursday.', exHe: 'המועד האחרון הוא ביום חמישי.' },
        { en: 'schedule', he: 'לוח זמנים', t: "סְקֶג'וּל", ex: 'My schedule is full this week.', exHe: 'לוח הזמנים שלי מלא השבוע.' },
        { en: 'break', he: 'הפסקה', t: 'בְּרֵייק', ex: 'We take a break at noon.', exHe: 'אנחנו עושים הפסקה בצהריים.' },
        { en: 'report', he: 'דוח', t: 'רִיפּוֹרְט', ex: 'The report is on your desk.', exHe: 'הדוח נמצא על השולחן שלך.' },
        { en: 'interview', he: 'ראיון', t: 'אִינְטֶרְוְיוּ', ex: 'I have an interview on Sunday.', exHe: 'יש לי ראיון ביום ראשון.' },
        { en: 'hire', he: 'להעסיק', t: 'הַאיֶר', ex: 'They want to hire two people.', exHe: 'הם רוצים להעסיק שני אנשים.' },
        { en: 'quit', he: 'להתפטר', t: 'קְוִויט', ex: 'He decided to quit his job.', exHe: 'הוא החליט להתפטר מהעבודה.' },
        { en: 'team', he: 'צוות', t: 'טִים', ex: 'Our team works very well.', exHe: 'הצוות שלנו עובד טוב מאוד.' },
        { en: 'manager', he: 'מנהל', t: "מֶנֶגֶ'ר", ex: 'The manager speaks with every worker.', exHe: 'המנהל מדבר עם כל עובד.' },
        { en: 'sign', he: 'לחתום', t: 'סַיין', ex: 'Please sign here at the bottom.', exHe: 'נא לחתום כאן למטה.' },
        { en: 'print', he: 'להדפיס', t: 'פְּרִינְט', ex: 'Can you print this page for me?', exHe: 'אתה יכול להדפיס לי את הדף הזה?' }
      ] },
      { id: 'travel', he: 'נסיעות ותחבורה', icon: '✈️', words: [
        { en: 'airport', he: 'שדה תעופה', t: 'אֶרְפּוֹרְט', ex: 'We arrive at the airport early.', exHe: 'אנחנו מגיעים לשדה התעופה מוקדם.' },
        { en: 'train', he: 'רכבת', t: 'טְרֵיין', ex: 'The train leaves at six.', exHe: 'הרכבת יוצאת בשש.' },
        { en: 'bus', he: 'אוטובוס', t: 'בַּאס', ex: 'The bus stops near my home.', exHe: 'האוטובוס עוצר ליד הבית שלי.' },
        { en: 'taxi', he: 'מונית', t: 'טֶקְסִי', ex: 'Let us take a taxi to the city.', exHe: 'בוא ניקח מונית לעיר.' },
        { en: 'station', he: 'תחנה', t: 'סְטֵיישֶׁן', ex: 'The station is very crowded today.', exHe: 'התחנה מאוד עמוסה היום.' },
        { en: 'map', he: 'מפה', t: 'מֶפּ', ex: 'Open the map on your phone.', exHe: 'פתח את המפה בטלפון שלך.' },
        { en: 'hotel', he: 'מלון', t: 'הוֹטֶל', ex: 'Our hotel is near the beach.', exHe: 'המלון שלנו ליד החוף.' },
        { en: 'suitcase', he: 'מזוודה', t: 'סוּטְקֵייס', ex: 'My suitcase is very heavy.', exHe: 'המזוודה שלי כבדה מאוד.' },
        { en: 'journey', he: 'מסע', t: "ג'וּרְנִי", ex: 'The journey takes five hours.', exHe: 'המסע נמשך חמש שעות.' },
        { en: 'arrive', he: 'להגיע', t: 'אֶרַייב', ex: 'We arrive in Madrid at night.', exHe: 'אנחנו מגיעים למדריד בלילה.' },
        { en: 'leave', he: 'לצאת (לעזוב)', t: 'לִיב', ex: 'They leave for Paris on Monday.', exHe: 'הם יוצאים לפריז ביום שני.' },
        { en: 'return', he: 'לחזור', t: 'רִיטֶרְן', ex: 'We return home next Sunday.', exHe: 'אנחנו חוזרים הביתה ביום ראשון הבא.' },
        { en: 'road', he: 'כביש', t: 'רוֹאוּד', ex: 'This road goes to Jerusalem.', exHe: 'הכביש הזה מוביל לירושלים.' },
        { en: 'bridge', he: 'גשר', t: "בְּרִידְג'", ex: 'The old bridge crosses the river.', exHe: 'הגשר הישן חוצה את הנהר.' },
        { en: 'traffic', he: 'תנועה (פקקים)', t: 'טְרֶפִיק', ex: 'There is heavy traffic this morning.', exHe: 'יש תנועה כבדה הבוקר.' },
        { en: 'driver', he: 'נהג', t: 'דְרַייבֶר', ex: 'The driver knows the way.', exHe: 'הנהג מכיר את הדרך.' },
        { en: 'passenger', he: 'נוסע', t: "פֶּסֶנְגֶ'ר", ex: 'Every passenger needs a seat.', exHe: 'כל נוסע צריך מושב.' },
        { en: 'platform', he: 'רציף', t: 'פְּלֶטְפוֹרְם', ex: 'The train waits at platform two.', exHe: 'הרכבת ממתינה ברציף שתיים.' },
        { en: 'tourist', he: 'תייר', t: 'טוּרִיסְט', ex: 'The tourist takes many photos.', exHe: 'התייר מצלם הרבה תמונות.' },
        { en: 'direction', he: 'כיוון', t: 'דַיירֶקְשֶׁן', ex: 'Which direction is the museum?', exHe: 'באיזה כיוון נמצא המוזיאון?' }
      ] },
      { id: 'shopping', he: 'קניות וכסף', icon: '🛒', words: [
        { en: 'money', he: 'כסף', t: 'מַאנִי', ex: 'I need money for the market.', exHe: 'אני צריך כסף לשוק.' },
        { en: 'price', he: 'מחיר', t: 'פְּרַייס', ex: 'The price is too high.', exHe: 'המחיר גבוה מדי.' },
        { en: 'cheap', he: 'זול', t: "צִ'יפּ", ex: 'These shoes are really cheap.', exHe: 'הנעליים האלה ממש זולות.' },
        { en: 'expensive', he: 'יקר', t: 'אֶקְסְפֶּנְסִיב', ex: 'This watch is too expensive.', exHe: 'השעון הזה יקר מדי.' },
        { en: 'sale', he: 'מבצע', t: 'סֵייל', ex: 'There is a big sale today.', exHe: 'יש מבצע גדול היום.' },
        { en: 'cash', he: 'מזומן', t: 'קֶש', ex: 'I pay in cash, not by card.', exHe: 'אני משלם במזומן, לא בכרטיס.' },
        { en: 'credit card', he: 'כרטיס אשראי', t: 'קְרֶדִיט קַארְד', ex: 'Can I pay by credit card?', exHe: 'אפשר לשלם בכרטיס אשראי?' },
        { en: 'wallet', he: 'ארנק', t: 'ווֹלֶט', ex: 'My wallet is in my bag.', exHe: 'הארנק שלי בתיק.' },
        { en: 'receipt', he: 'קבלה', t: 'רִיסִיט', ex: 'Keep the receipt, just in case.', exHe: 'שמור את הקבלה, ליתר ביטחון.' },
        { en: 'discount', he: 'הנחה', t: 'דִיסְקַאוּנְט', ex: 'You get a ten percent discount.', exHe: 'אתה מקבל עשרה אחוזי הנחה.' },
        { en: 'market', he: 'שוק', t: 'מַארְקֶט', ex: 'The market is open on Friday.', exHe: 'השוק פתוח ביום שישי.' },
        { en: 'supermarket', he: 'סופרמרקט', t: 'סוּפֶּרְמַארְקֶט', ex: 'The supermarket closes at ten.', exHe: 'הסופרמרקט נסגר בעשר.' },
        { en: 'customer', he: 'לקוח', t: 'קַאסְטוֹמֶר', ex: 'The customer is always right.', exHe: 'הלקוח תמיד צודק.' },
        { en: 'pay', he: 'לשלם', t: 'פֵּיי', ex: 'You can pay at the counter.', exHe: 'אפשר לשלם בדלפק.' },
        { en: 'cost', he: 'לעלות (במחיר)', t: 'קוֹסְט', ex: 'How much does it cost?', exHe: 'כמה זה עולה?' },
        { en: 'spend', he: 'להוציא (כסף)', t: 'סְפֶּנְד', ex: 'Do not spend all your money.', exHe: 'אל תוציא את כל הכסף שלך.' },
        { en: 'save', he: 'לחסוך', t: 'סֵייב', ex: 'We save money every month.', exHe: 'אנחנו חוסכים כסף כל חודש.' },
        { en: 'basket', he: 'סל', t: 'בַּאסְקֶט', ex: 'Put the bread in the basket.', exHe: 'שים את הלחם בסל.' },
        { en: 'cashier', he: 'קופאי', t: 'קֶשִׁיר', ex: 'The cashier gives me the change.', exHe: 'הקופאי נותן לי את העודף.' },
        { en: 'change', he: 'עודף', t: "צֵ'יינְג'", ex: 'Here is your change, sir.', exHe: 'הנה העודף שלך, אדוני.' }
      ] },
      { id: 'health', he: 'בריאות וגוף', icon: '🩺', words: [
        { en: 'nurse', he: 'אחות (רפואית)', t: 'נֶרְס', ex: 'The nurse checks my temperature.', exHe: 'האחות בודקת לי את החום.' },
        { en: 'hospital', he: 'בית חולים', t: 'הוֹסְפִּיטֶל', ex: 'The hospital is near the center.', exHe: 'בית החולים נמצא ליד המרכז.' },
        { en: 'dentist', he: 'רופא שיניים', t: 'דֶנְטִיסְט', ex: 'I visit the dentist twice a year.', exHe: 'אני מבקר אצל רופא השיניים פעמיים בשנה.' },
        { en: 'tooth', he: 'שן', t: "טוּת'", ex: 'My tooth hurts a little.', exHe: 'השן שלי כואבת קצת.' },
        { en: 'pain', he: 'כאב', t: 'פֵּיין', ex: 'The pain is almost gone.', exHe: 'הכאב כמעט עבר.' },
        { en: 'cough', he: 'שיעול', t: 'קוֹף', ex: 'This cough started two days ago.', exHe: 'השיעול הזה התחיל לפני יומיים.' },
        { en: 'cold', he: 'הצטננות', t: 'קוֹלְד', ex: 'I have a bad cold.', exHe: 'יש לי הצטננות חזקה.' },
        { en: 'flu', he: 'שפעת', t: 'פְלוּ', ex: 'Many people have the flu now.', exHe: 'הרבה אנשים חולים בשפעת עכשיו.' },
        { en: 'pill', he: 'כדור (תרופה)', t: 'פִּיל', ex: 'Take one pill after dinner.', exHe: 'קח כדור אחד אחרי ארוחת הערב.' },
        { en: 'appointment', he: 'תור (לרופא)', t: 'אַפּוֹיְנְטְמֶנְט', ex: 'My appointment is at four.', exHe: 'התור שלי בשעה ארבע.' },
        { en: 'sick', he: 'חולה', t: 'סִיק', ex: 'He feels sick this morning.', exHe: 'הוא מרגיש חולה הבוקר.' },
        { en: 'hand', he: 'יד', t: 'הֶנְד', ex: 'Wash your hands before dinner.', exHe: 'שטוף ידיים לפני ארוחת הערב.' },
        { en: 'leg', he: 'רגל', t: 'לֶג', ex: 'My leg is tired after the run.', exHe: 'הרגל שלי עייפה אחרי הריצה.' },
        { en: 'eye', he: 'עין', t: 'אַיי', ex: 'My right eye is red.', exHe: 'העין הימנית שלי אדומה.' },
        { en: 'ear', he: 'אוזן', t: 'אִיר', ex: 'My left ear hurts at night.', exHe: 'האוזן השמאלית שלי כואבת בלילה.' },
        { en: 'heart', he: 'לב', t: 'הַארְט', ex: 'A strong heart needs exercise.', exHe: 'לב חזק צריך פעילות גופנית.' },
        { en: 'stomach', he: 'בטן', t: 'סְטַאמֶק', ex: 'My stomach is full.', exHe: 'הבטן שלי מלאה.' },
        { en: 'back', he: 'גב', t: 'בֶּק', ex: 'His back hurts after work.', exHe: 'הגב שלו כואב אחרי העבודה.' },
        { en: 'breathe', he: 'לנשום', t: "בְּרִיד'", ex: 'Breathe slowly and stay calm.', exHe: 'נשום לאט והישאר רגוע.' },
        { en: 'strong', he: 'חזק', t: 'סְטְרוֹנְג', ex: 'She is strong and healthy.', exHe: 'היא חזקה ובריאה.' }
      ] },
      { id: 'home', he: 'בית ודירה', icon: '🏠', words: [
        { en: 'apartment', he: 'דירה', t: 'אַפַּרְטְמֶנְט', ex: 'Our apartment is on the third floor.', exHe: 'הדירה שלנו בקומה השלישית.' },
        { en: 'bedroom', he: 'חדר שינה', t: 'בֶּדְרוּם', ex: 'The bedroom has a big closet.', exHe: 'בחדר השינה יש ארון גדול.' },
        { en: 'bathroom', he: 'חדר אמבטיה', t: "בַּאתְ'רוּם", ex: 'The bathroom is down the hall.', exHe: 'חדר האמבטיה בהמשך המסדרון.' },
        { en: 'living room', he: 'סלון', t: 'לִיבִינְג רוּם', ex: 'We watch TV in the living room.', exHe: 'אנחנו רואים טלוויזיה בסלון.' },
        { en: 'bed', he: 'מיטה', t: 'בֶּד', ex: 'The bed is very comfortable.', exHe: 'המיטה מאוד נוחה.' },
        { en: 'sofa', he: 'ספה', t: 'סוֹפָה', ex: 'The cat sleeps on the sofa.', exHe: 'החתול ישן על הספה.' },
        { en: 'shower', he: 'מקלחת', t: 'שַׁאוּאֶר', ex: 'I take a shower every evening.', exHe: 'אני מתקלח כל ערב.' },
        { en: 'toilet', he: 'שירותים', t: 'טוֹיְלֶט', ex: 'The toilet is next to the shower.', exHe: 'השירותים ליד המקלחת.' },
        { en: 'floor', he: 'רצפה', t: 'פְלוֹר', ex: 'The floor is clean now.', exHe: 'הרצפה נקייה עכשיו.' },
        { en: 'wall', he: 'קיר', t: 'ווֹל', ex: 'There is a picture on the wall.', exHe: 'יש תמונה על הקיר.' },
        { en: 'roof', he: 'גג', t: 'רוּף', ex: 'The roof needs a small repair.', exHe: 'הגג צריך תיקון קטן.' },
        { en: 'garden', he: 'גינה', t: 'גַארְדֶן', ex: 'The garden is full of flowers.', exHe: 'הגינה מלאה בפרחים.' },
        { en: 'balcony', he: 'מרפסת', t: 'בַּלְקוֹנִי', ex: 'We drink coffee on the balcony.', exHe: 'אנחנו שותים קפה במרפסת.' },
        { en: 'stairs', he: 'מדרגות', t: 'סְטֶרְס', ex: 'Take the stairs to the second floor.', exHe: 'עלה במדרגות לקומה השנייה.' },
        { en: 'elevator', he: 'מעלית', t: 'אֶלֶבֵייטֶר', ex: 'The elevator is out of order.', exHe: 'המעלית מקולקלת.' },
        { en: 'key', he: 'מפתח', t: 'קִי', ex: 'The key is under the mat.', exHe: 'המפתח נמצא מתחת לשטיח.' },
        { en: 'lamp', he: 'מנורה', t: 'לֶמְפּ', ex: 'Turn on the lamp, it is dark.', exHe: 'הדלק את המנורה, חשוך.' },
        { en: 'mirror', he: 'מראה', t: 'מִירוֹר', ex: 'There is a mirror near the door.', exHe: 'יש מראה ליד הדלת.' },
        { en: 'fridge', he: 'מקרר', t: "פְרִידְג'", ex: 'The fridge is almost empty.', exHe: 'המקרר כמעט ריק.' },
        { en: 'neighbor', he: 'שכן', t: 'נֵייבּוֹר', ex: 'Our neighbor is very quiet.', exHe: 'השכן שלנו מאוד שקט.' }
      ] },
      { id: 'weather', he: 'טבע ומזג אוויר', icon: '🌦️', words: [
        { en: 'sun', he: 'שמש', t: 'סַאן', ex: 'The sun is strong today.', exHe: 'השמש חזקה היום.' },
        { en: 'rain', he: 'גשם', t: 'רֵיין', ex: 'The rain stopped an hour ago.', exHe: 'הגשם פסק לפני שעה.' },
        { en: 'snow', he: 'שלג', t: 'סְנוֹאוּ', ex: 'Snow is rare in Tel Aviv.', exHe: 'שלג הוא דבר נדיר בתל אביב.' },
        { en: 'wind', he: 'רוח', t: 'וִוינְד', ex: 'The wind is cold tonight.', exHe: 'הרוח קרה הלילה.' },
        { en: 'cloud', he: 'ענן', t: 'קְלַאוּד', ex: 'There is one small cloud above.', exHe: 'יש ענן קטן אחד למעלה.' },
        { en: 'storm', he: 'סערה', t: 'סְטוֹרְם', ex: 'A big storm is coming tomorrow.', exHe: 'סערה גדולה מגיעה מחר.' },
        { en: 'hot', he: 'חם', t: 'הוֹט', ex: 'August is very hot here.', exHe: 'אוגוסט חם מאוד כאן.' },
        { en: 'warm', he: 'חמים', t: 'ווֹרְם', ex: 'The water is warm and nice.', exHe: 'המים חמימים ונעימים.' },
        { en: 'sunny', he: 'שמשי', t: 'סַאנִי', ex: 'It is sunny most of the year.', exHe: 'שמשי רוב ימות השנה.' },
        { en: 'cloudy', he: 'מעונן', t: 'קְלַאוּדִי', ex: 'The morning was gray and cloudy.', exHe: 'הבוקר היה אפור ומעונן.' },
        { en: 'umbrella', he: 'מטרייה', t: 'אַמְבְּרֶלָה', ex: 'Take an umbrella with you.', exHe: 'קח איתך מטרייה.' },
        { en: 'temperature', he: 'טמפרטורה', t: "טֶמְפְּרֶצֶ'ר", ex: 'The temperature drops at night.', exHe: 'הטמפרטורה יורדת בלילה.' },
        { en: 'sky', he: 'שמיים', t: 'סְקַיי', ex: 'The sky is blue and clear.', exHe: 'השמיים כחולים ובהירים.' },
        { en: 'sea', he: 'ים', t: 'סִי', ex: 'The sea is calm this morning.', exHe: 'הים רגוע הבוקר.' },
        { en: 'mountain', he: 'הר', t: 'מַאוּנְטֶן', ex: 'The mountain is white in winter.', exHe: 'ההר לבן בחורף.' },
        { en: 'river', he: 'נהר', t: 'רִיבֶר', ex: 'The river runs through the city.', exHe: 'הנהר עובר דרך העיר.' },
        { en: 'tree', he: 'עץ', t: 'טְרִי', ex: 'The old tree gives good shade.', exHe: 'העץ הזקן נותן צל טוב.' },
        { en: 'flower', he: 'פרח', t: 'פְלַאוּאֶר', ex: 'This flower opens in spring.', exHe: 'הפרח הזה נפתח באביב.' },
        { en: 'beach', he: 'חוף', t: "בִּיץ'", ex: 'The beach is empty in winter.', exHe: 'החוף ריק בחורף.' },
        { en: 'forest', he: 'יער', t: 'פוֹרֶסְט', ex: 'We walk in the forest on Saturday.', exHe: 'אנחנו מטיילים ביער בשבת.' }
      ] },
      { id: 'feelings', he: 'רגשות', icon: '💚', words: [
        { en: 'sad', he: 'עצוב', t: 'סֶד', ex: 'The movie made me sad.', exHe: 'הסרט העציב אותי.' },
        { en: 'angry', he: 'כועס', t: 'אֶנְגְרִי', ex: 'Do not be angry with me.', exHe: 'אל תכעס עליי.' },
        { en: 'afraid', he: 'מפחד', t: 'אַפְרֵייד', ex: 'The child is afraid of dogs.', exHe: 'הילד מפחד מכלבים.' },
        { en: 'excited', he: 'נרגש', t: 'אֶקְסַייטֶד', ex: 'We are excited about the wedding.', exHe: 'אנחנו נרגשים לקראת החתונה.' },
        { en: 'bored', he: 'משועמם', t: 'בּוֹרְד', ex: 'The students look bored today.', exHe: 'התלמידים נראים משועממים היום.' },
        { en: 'surprised', he: 'מופתע', t: 'סֶרְפְּרַייזְד', ex: 'She was surprised by the gift.', exHe: 'היא הופתעה מהמתנה.' },
        { en: 'proud', he: 'גאה', t: 'פְּרַאוּד', ex: 'I am proud of my daughter.', exHe: 'אני גאה בבת שלי.' },
        { en: 'lonely', he: 'בודד', t: 'לוֹנְלִי', ex: 'He feels lonely in the big city.', exHe: 'הוא מרגיש בודד בעיר הגדולה.' },
        { en: 'nervous', he: 'לחוץ (עצבני)', t: 'נֶרְבֶס', ex: 'I am nervous before the test.', exHe: 'אני לחוץ לפני המבחן.' },
        { en: 'calm', he: 'רגוע', t: 'קַאם', ex: 'Stay calm and speak clearly.', exHe: 'הישאר רגוע ודבר ברור.' },
        { en: 'glad', he: 'שמח (מרוצה)', t: 'גְלֶד', ex: 'I am glad you are here.', exHe: 'אני שמח שאתה כאן.' },
        { en: 'upset', he: 'נסער (מוטרד)', t: 'אַפְּסֶט', ex: 'She is upset about the news.', exHe: 'היא מוטרדת מהחדשות.' },
        { en: 'thirsty', he: 'צמא', t: "תֶ'רְסְטִי", ex: 'The runners are very thirsty.', exHe: 'הרצים צמאים מאוד.' },
        { en: 'comfortable', he: 'נוח', t: 'קַאמְפְטֶבֶּל', ex: 'This chair is very comfortable.', exHe: 'הכיסא הזה מאוד נוח.' },
        { en: 'stressed', he: 'לחוץ (בלחץ)', t: 'סְטְרֶסְט', ex: 'He is stressed before the deadline.', exHe: 'הוא לחוץ לפני המועד האחרון.' },
        { en: 'hope', he: 'לקוות', t: 'הוֹפּ', ex: 'I hope you feel better.', exHe: 'אני מקווה שתרגיש טוב יותר.' },
        { en: 'smile', he: 'חיוך', t: 'סְמַייל', ex: 'Her smile makes everyone happy.', exHe: 'החיוך שלה משמח את כולם.' },
        { en: 'cry', he: 'לבכות', t: 'קְרַיי', ex: 'Babies cry when they are hungry.', exHe: 'תינוקות בוכים כשהם רעבים.' },
        { en: 'laugh', he: 'לצחוק', t: 'לַאף', ex: 'We laugh a lot together.', exHe: 'אנחנו צוחקים הרבה יחד.' },
        { en: 'feel', he: 'להרגיש', t: 'פִיל', ex: 'I feel much better today.', exHe: 'אני מרגיש הרבה יותר טוב היום.' }
      ] },
      { id: 'time', he: 'זמן ולוח שנה', icon: '🕒', words: [
        { en: 'morning', he: 'בוקר', t: 'מוֹרְנִינְג', ex: 'The morning is my best time.', exHe: 'הבוקר הוא הזמן הכי טוב שלי.' },
        { en: 'evening', he: 'ערב', t: 'אִיבְנִינְג', ex: 'In the evening we watch the news.', exHe: 'בערב אנחנו רואים את החדשות.' },
        { en: 'night', he: 'לילה', t: 'נַייט', ex: 'The night is quiet here.', exHe: 'הלילה שקט כאן.' },
        { en: 'noon', he: 'צהריים', t: 'נוּן', ex: 'The office closes at noon on Friday.', exHe: 'המשרד נסגר בצהריים ביום שישי.' },
        { en: 'midnight', he: 'חצות', t: 'מִידְנַייט', ex: 'The party ended at midnight.', exHe: 'המסיבה הסתיימה בחצות.' },
        { en: 'hour', he: 'שעה', t: 'אַוּאֶר', ex: 'The lesson takes one hour.', exHe: 'השיעור נמשך שעה אחת.' },
        { en: 'minute', he: 'דקה', t: 'מִינִיט', ex: 'Wait a minute, I am coming.', exHe: 'חכה דקה, אני בא.' },
        { en: 'week', he: 'שבוע', t: 'וִויק', ex: 'This week is very short.', exHe: 'השבוע הזה קצר מאוד.' },
        { en: 'month', he: 'חודש', t: "מַאנְת'", ex: 'This month has thirty days.', exHe: 'בחודש הזה יש שלושים יום.' },
        { en: 'year', he: 'שנה', t: 'יִיר', ex: 'The year passes so fast.', exHe: 'השנה עוברת כל כך מהר.' },
        { en: 'date', he: 'תאריך', t: 'דֵייט', ex: 'What is the date today?', exHe: 'מה התאריך היום?' },
        { en: 'calendar', he: 'לוח שנה', t: 'קֶלֶנְדֶר', ex: 'The meeting is on the calendar.', exHe: 'הפגישה רשומה בלוח השנה.' },
        { en: 'early', he: 'מוקדם', t: 'אֶרְלִי', ex: 'I wake up early every day.', exHe: 'אני מתעורר מוקדם כל יום.' },
        { en: 'late', he: 'מאוחר', t: 'לֵייט', ex: 'Sorry, I am a little late.', exHe: 'סליחה, אני קצת מאחר.' },
        { en: 'birthday', he: 'יום הולדת', t: "בֶּרְת'דֵיי", ex: 'Her birthday is in March.', exHe: 'יום ההולדת שלה במרץ.' },
        { en: 'holiday', he: 'חג (חופשה)', t: 'הוֹלִידֵיי', ex: 'The holiday starts on Wednesday.', exHe: 'החג מתחיל ביום רביעי.' },
        { en: 'season', he: 'עונה', t: 'סִיזוֹן', ex: 'Spring is my favorite season.', exHe: 'האביב הוא העונה האהובה עליי.' },
        { en: 'spring', he: 'אביב', t: 'סְפְּרִינְג', ex: 'In spring everything turns green.', exHe: 'באביב הכול נהיה ירוק.' },
        { en: 'summer', he: 'קיץ', t: 'סַאמֶר', ex: 'The summer here is long and hot.', exHe: 'הקיץ כאן ארוך וחם.' },
        { en: 'winter', he: 'חורף', t: 'וִוינְטֶר', ex: 'In winter it gets dark early.', exHe: 'בחורף מחשיך מוקדם.' }
      ] },
      { id: 'clothes', he: 'בגדים', icon: '👕', words: [
        { en: 'shirt', he: 'חולצה', t: 'שֶׁרְט', ex: 'The blue shirt fits you well.', exHe: 'החולצה הכחולה מתאימה לך.' },
        { en: 'pants', he: 'מכנסיים', t: 'פֶּנְץ', ex: 'These pants are too long.', exHe: 'המכנסיים האלה ארוכים מדי.' },
        { en: 'dress', he: 'שמלה', t: 'דְרֶס', ex: 'She wears a red dress.', exHe: 'היא לובשת שמלה אדומה.' },
        { en: 'skirt', he: 'חצאית', t: 'סְקֶרְט', ex: 'The skirt matches the shoes.', exHe: 'החצאית מתאימה לנעליים.' },
        { en: 'coat', he: 'מעיל', t: 'קוֹאוּט', ex: 'Take a coat, it is cold outside.', exHe: 'קח מעיל, קר בחוץ.' },
        { en: 'jacket', he: "ז'קט", t: "גֶ'קֶט", ex: 'The jacket has deep pockets.', exHe: "לז'קט יש כיסים עמוקים." },
        { en: 'shoes', he: 'נעליים', t: 'שׁוּז', ex: 'My new shoes are comfortable.', exHe: 'הנעליים החדשות שלי נוחות.' },
        { en: 'socks', he: 'גרביים', t: 'סוֹקְס', ex: 'I need clean socks for tomorrow.', exHe: 'אני צריך גרביים נקיים למחר.' },
        { en: 'hat', he: 'כובע', t: 'הֶט', ex: 'Wear a hat in the sun.', exHe: 'חבוש כובע בשמש.' },
        { en: 'scarf', he: 'צעיף', t: 'סְקַארְף', ex: 'The scarf keeps my neck warm.', exHe: 'הצעיף שומר על חום הצוואר שלי.' },
        { en: 'gloves', he: 'כפפות', t: 'גְלַאבְס', ex: 'Wear gloves when it snows.', exHe: 'לבש כפפות כשיורד שלג.' },
        { en: 'sweater', he: 'סוודר', t: 'סְוֶוטֶר', ex: 'This sweater is made of wool.', exHe: 'הסוודר הזה עשוי צמר.' },
        { en: 'belt', he: 'חגורה', t: 'בֶּלְט', ex: 'I need a belt for these pants.', exHe: 'אני צריך חגורה למכנסיים האלה.' },
        { en: 'tie', he: 'עניבה', t: 'טַיי', ex: 'He wears a tie to meetings.', exHe: 'הוא עונב עניבה לפגישות.' },
        { en: 'pocket', he: 'כיס', t: 'פּוֹקֶט', ex: 'The key is in my pocket.', exHe: 'המפתח נמצא בכיס שלי.' },
        { en: 'size', he: 'מידה', t: 'סַייז', ex: 'Do you have a bigger size?', exHe: 'יש לך מידה גדולה יותר?' },
        { en: 'wear', he: 'ללבוש', t: 'וֶור', ex: 'What will you wear tonight?', exHe: 'מה תלבש הערב?' },
        { en: 'fit', he: 'להתאים (במידה)', t: 'פִיט', ex: 'These jeans fit me perfectly.', exHe: "הג'ינס הזה מתאים לי בדיוק." },
        { en: 'try on', he: 'למדוד (בגד)', t: 'טְרַיי אוֹן', ex: 'Can I try on this dress?', exHe: 'אפשר למדוד את השמלה הזאת?' },
        { en: 'fashion', he: 'אופנה', t: 'פֶשֶׁן', ex: 'She loves Italian fashion.', exHe: 'היא אוהבת אופנה איטלקית.' }
      ] },
      { id: 'sport', he: 'ספורט ופנאי', icon: '⚽', words: [
        { en: 'game', he: 'משחק', t: 'גֵיים', ex: 'The game starts at eight.', exHe: 'המשחק מתחיל בשמונה.' },
        { en: 'ball', he: 'כדור (משחק)', t: 'בּוֹל', ex: 'Throw the ball to me.', exHe: 'זרוק אליי את הכדור.' },
        { en: 'football', he: 'כדורגל', t: 'פוּטְבּוֹל', ex: 'We play football on Saturday.', exHe: 'אנחנו משחקים כדורגל בשבת.' },
        { en: 'basketball', he: 'כדורסל', t: 'בַּאסְקֶטְבּוֹל', ex: 'My son loves basketball.', exHe: 'הבן שלי אוהב כדורסל.' },
        { en: 'swimming', he: 'שחייה', t: 'סְוִוימִינְג', ex: 'Swimming is great exercise.', exHe: 'שחייה היא פעילות גופנית מצוינת.' },
        { en: 'running', he: 'ריצה', t: 'רַאנִינְג', ex: 'Running keeps me in shape.', exHe: 'ריצה שומרת עליי בכושר.' },
        { en: 'gym', he: 'חדר כושר', t: "גִ'ים", ex: 'I go to the gym twice a week.', exHe: 'אני הולך לחדר כושר פעמיים בשבוע.' },
        { en: 'exercise', he: 'התעמלות', t: 'אֶקְסֶרְסַייז', ex: 'A little exercise every day helps.', exHe: 'קצת התעמלות כל יום עוזרת.' },
        { en: 'coach', he: 'מאמן', t: "קוֹאוּץ'", ex: 'The coach is proud of the team.', exHe: 'המאמן גאה בקבוצה.' },
        { en: 'player', he: 'שחקן', t: 'פְּלֵייֶר', ex: 'He is the best player here.', exHe: 'הוא השחקן הכי טוב כאן.' },
        { en: 'win', he: 'לנצח', t: 'וִוין', ex: 'I hope we win tonight.', exHe: 'אני מקווה שננצח הערב.' },
        { en: 'lose', he: 'להפסיד', t: 'לוּז', ex: 'Nobody likes to lose.', exHe: 'אף אחד לא אוהב להפסיד.' },
        { en: 'score', he: 'תוצאה', t: 'סְקוֹר', ex: 'What is the score now?', exHe: 'מה התוצאה עכשיו?' },
        { en: 'race', he: 'מרוץ', t: 'רֵייס', ex: 'The race begins at the park.', exHe: 'המרוץ מתחיל בפארק.' },
        { en: 'bicycle', he: 'אופניים', t: 'בַּייסִיקֶל', ex: 'I ride my bicycle to the sea.', exHe: 'אני רוכב על האופניים שלי לים.' },
        { en: 'match', he: 'משחק (תחרות)', t: "מֶץ'", ex: 'The match ended without goals.', exHe: 'המשחק הסתיים ללא שערים.' },
        { en: 'park', he: 'פארק', t: 'פַּארְק', ex: 'The park is full on Saturday.', exHe: 'הפארק מלא בשבת.' },
        { en: 'dance', he: 'לרקוד', t: 'דֶנְס', ex: 'They dance every Friday night.', exHe: 'הם רוקדים כל יום שישי בערב.' },
        { en: 'relax', he: 'להירגע', t: 'רִילֶקְס', ex: 'I relax with music at night.', exHe: 'אני נרגע עם מוזיקה בלילה.' },
        { en: 'fun', he: 'כיף', t: 'פַאן', ex: 'The picnic was great fun.', exHe: 'הפיקניק היה כיף גדול.' }
      ] },
      { id: 'tech', he: 'טכנולוגיה ומסכים', icon: '📱', words: [
        { en: 'phone', he: 'טלפון', t: 'פוֹן', ex: 'My phone rings all day.', exHe: 'הטלפון שלי מצלצל כל היום.' },
        { en: 'computer', he: 'מחשב', t: 'קוֹמְפְּיוּטֶר', ex: 'The computer is slow today.', exHe: 'המחשב איטי היום.' },
        { en: 'screen', he: 'מסך', t: 'סְקְרִין', ex: 'The screen is too bright.', exHe: 'המסך בהיר מדי.' },
        { en: 'internet', he: 'אינטרנט', t: 'אִינְטֶרְנֶט', ex: 'The internet is down again.', exHe: 'האינטרנט נפל שוב.' },
        { en: 'website', he: 'אתר אינטרנט', t: 'וֶובְּסַייט', ex: 'This website has good recipes.', exHe: 'באתר הזה יש מתכונים טובים.' },
        { en: 'password', he: 'סיסמה', t: 'פֶּסְווֹרְד', ex: 'Change your password every year.', exHe: 'החלף את הסיסמה שלך כל שנה.' },
        { en: 'message', he: 'הודעה', t: "מֶסִידְג'", ex: 'Send me a message later.', exHe: 'שלח לי הודעה אחר כך.' },
        { en: 'camera', he: 'מצלמה', t: 'קֶמֶרָה', ex: 'The camera takes beautiful pictures.', exHe: 'המצלמה מצלמת תמונות יפות.' },
        { en: 'photo', he: 'תמונה', t: 'פוֹטוֹ', ex: 'This photo is from our wedding.', exHe: 'התמונה הזאת מהחתונה שלנו.' },
        { en: 'video', he: 'סרטון', t: 'וִידֵאוֹ', ex: 'The video is two minutes long.', exHe: 'הסרטון באורך שתי דקות.' },
        { en: 'app', he: 'אפליקציה', t: 'אֶפּ', ex: 'This app is free and simple.', exHe: 'האפליקציה הזאת חינמית ופשוטה.' },
        { en: 'battery', he: 'סוללה', t: 'בֶּטֶרִי', ex: 'The battery lasts all day.', exHe: 'הסוללה מחזיקה כל היום.' },
        { en: 'charger', he: 'מטען', t: "צַ'ארְגֶ'ר", ex: 'I left my charger at home.', exHe: 'השארתי את המטען שלי בבית.' },
        { en: 'wifi', he: 'וויי-פיי', t: 'וַוייפַיי', ex: 'The wifi is free in the hotel.', exHe: 'הוויי-פיי חינם במלון.' },
        { en: 'keyboard', he: 'מקלדת', t: 'קִיבּוֹרְד', ex: 'The keyboard needs new batteries.', exHe: 'המקלדת צריכה סוללות חדשות.' },
        { en: 'mouse', he: 'עכבר (מחשב)', t: 'מַאוּס', ex: 'Click with the right mouse button.', exHe: 'לחץ עם הכפתור הימני של העכבר.' },
        { en: 'file', he: 'קובץ', t: 'פַייל', ex: 'Save the file before you close.', exHe: 'שמור את הקובץ לפני שאתה סוגר.' },
        { en: 'download', he: 'להוריד (קובץ)', t: 'דַאוּנְלוֹאוּד', ex: 'You can download the form here.', exHe: 'אפשר להוריד את הטופס כאן.' },
        { en: 'click', he: 'ללחוץ (בעכבר)', t: 'קְלִיק', ex: 'Click on the blue button.', exHe: 'לחץ על הכפתור הכחול.' },
        { en: 'online', he: 'מקוון', t: 'אוֹנְלַיין', ex: 'We meet online on Tuesday.', exHe: 'אנחנו נפגשים אונליין ביום שלישי.' }
      ] },
      { id: 'restaurant', he: 'במסעדה', icon: '🍽️', words: [
        { en: 'waiter', he: 'מלצר', t: 'וֵייטֶר', ex: 'The waiter brings the bread.', exHe: 'המלצר מביא את הלחם.' },
        { en: 'reserve', he: 'להזמין מקום', t: 'רִיזֶרְב', ex: 'I want to reserve a table for two.', exHe: 'אני רוצה להזמין שולחן לשניים.' },
        { en: 'dish', he: 'מנה', t: 'דִישׁ', ex: 'This dish comes with rice.', exHe: 'המנה הזאת מגיעה עם אורז.' },
        { en: 'dessert', he: 'קינוח', t: 'דִיזֶרְט', ex: 'The chocolate dessert is wonderful.', exHe: 'קינוח השוקולד נפלא.' },
        { en: 'starter', he: 'מנה ראשונה', t: 'סְטַארְטֶר', ex: 'The starter arrives before the soup.', exHe: 'המנה הראשונה מגיעה לפני המרק.' },
        { en: 'main course', he: 'מנה עיקרית', t: 'מֵיין קוֹרְס', ex: 'The main course is grilled meat.', exHe: 'המנה העיקרית היא בשר על האש.' },
        { en: 'glass', he: 'כוס', t: 'גְלַאס', ex: 'A glass of red wine, please.', exHe: 'כוס יין אדום, בבקשה.' },
        { en: 'bottle', he: 'בקבוק', t: 'בּוֹטֶל', ex: 'We need a bottle of cold water.', exHe: 'אנחנו צריכים בקבוק מים קרים.' },
        { en: 'fork', he: 'מזלג', t: 'פוֹרְק', ex: 'My fork fell on the floor.', exHe: 'המזלג שלי נפל על הרצפה.' },
        { en: 'knife', he: 'סכין', t: 'נַייף', ex: 'This knife does not cut well.', exHe: 'הסכין הזאת לא חותכת טוב.' },
        { en: 'spoon', he: 'כף', t: 'סְפּוּן', ex: 'I need a spoon for the soup.', exHe: 'אני צריך כף למרק.' },
        { en: 'plate', he: 'צלחת', t: 'פְּלֵייט', ex: 'The plate is still hot.', exHe: 'הצלחת עדיין חמה.' },
        { en: 'napkin', he: 'מפית', t: 'נֶפְּקִין', ex: 'Can I have a napkin, please?', exHe: 'אפשר לקבל מפית, בבקשה?' },
        { en: 'bill', he: 'חשבון', t: 'בִּיל', ex: 'The bill comes to eighty shekels.', exHe: 'החשבון יוצא שמונים שקלים.' },
        { en: 'wine', he: 'יין', t: 'וַויין', ex: 'This wine is from the Galilee.', exHe: 'היין הזה מהגליל.' },
        { en: 'beer', he: 'בירה', t: 'בִּיר', ex: 'A cold beer on a hot day.', exHe: 'בירה קרה ביום חם.' },
        { en: 'ice cream', he: 'גלידה', t: 'אַייס קְרִים', ex: 'The children want ice cream.', exHe: 'הילדים רוצים גלידה.' },
        { en: 'sweet', he: 'מתוק', t: 'סְוִויט', ex: 'The cake is too sweet for me.', exHe: 'העוגה מתוקה מדי בשבילי.' },
        { en: 'sour', he: 'חמוץ', t: 'סַאוּאֶר', ex: 'The lemonade is a little sour.', exHe: 'הלימונדה קצת חמוצה.' },
        { en: 'fresh', he: 'טרי', t: 'פְרֶשׁ', ex: 'The bread here is always fresh.', exHe: 'הלחם כאן תמיד טרי.' }
      ] },
      { id: 'help', he: 'חירום ועזרה', icon: '🆘', words: [
        { en: 'emergency', he: 'מקרה חירום', t: "אִימֶרְגֶ'נְסִי", ex: 'In an emergency, call this number.', exHe: 'במקרה חירום, התקשר למספר הזה.' },
        { en: 'police', he: 'משטרה', t: 'פּוֹלִיס', ex: 'The police station is nearby.', exHe: 'תחנת המשטרה קרובה.' },
        { en: 'fire', he: 'אש (שריפה)', t: 'פַאיֶר', ex: 'Fire! Everyone out, quickly!', exHe: 'שריפה! כולם החוצה, מהר!' },
        { en: 'ambulance', he: 'אמבולנס', t: 'אֶמְבּיוּלֶנְס', ex: 'The ambulance arrived in five minutes.', exHe: 'האמבולנס הגיע תוך חמש דקות.' },
        { en: 'danger', he: 'סכנה', t: "דֵיינְגֶ'ר", ex: 'Danger! Deep water ahead.', exHe: 'סכנה! מים עמוקים לפניך.' },
        { en: 'dangerous', he: 'מסוכן', t: "דֵיינְגֶ'רֶס", ex: 'This road is dangerous at night.', exHe: 'הכביש הזה מסוכן בלילה.' },
        { en: 'careful', he: 'זהיר', t: 'קֶרְפוּל', ex: 'Be careful on the wet floor.', exHe: 'היזהר על הרצפה הרטובה.' },
        { en: 'accident', he: 'תאונה', t: 'אֶקְסִידֶנְט', ex: 'There was an accident on the road.', exHe: 'הייתה תאונה בכביש.' },
        { en: 'call', he: 'להתקשר', t: 'קוֹל', ex: 'Call me when you arrive.', exHe: 'התקשר אליי כשאתה מגיע.' },
        { en: 'safe', he: 'בטוח (מוגן)', t: 'סֵייף', ex: 'The children are safe at home.', exHe: 'הילדים בטוחים בבית.' },
        { en: 'warning', he: 'אזהרה', t: 'ווֹרְנִינְג', ex: 'Read the warning on the sign.', exHe: 'קרא את האזהרה על השלט.' },
        { en: 'exit', he: 'יציאה', t: 'אֶקְזִיט', ex: 'The exit is on the left.', exHe: 'היציאה נמצאת בצד שמאל.' },
        { en: 'entrance', he: 'כניסה', t: 'אֶנְטְרֶנְס', ex: 'The entrance is behind the building.', exHe: 'הכניסה מאחורי הבניין.' },
        { en: 'push', he: 'לדחוף', t: 'פּוּשׁ', ex: 'Push the door to open it.', exHe: 'דחוף את הדלת כדי לפתוח אותה.' },
        { en: 'pull', he: 'למשוך', t: 'פּוּל', ex: 'Pull the handle, do not push.', exHe: 'משוך את הידית, אל תדחף.' },
        { en: 'open', he: 'פתוח', t: 'אוֹפֶּן', ex: 'The clinic is open until noon.', exHe: 'המרפאה פתוחה עד הצהריים.' },
        { en: 'closed', he: 'סגור', t: 'קְלוֹזְד', ex: 'The bank is closed on Saturday.', exHe: 'הבנק סגור בשבת.' },
        { en: 'wait', he: 'לחכות', t: 'וֵייט', ex: 'Wait for the green light.', exHe: 'חכה לאור הירוק.' },
        { en: 'repeat', he: 'לחזור על', t: 'רִיפִּיט', ex: 'Can you repeat that more slowly?', exHe: 'אתה יכול לחזור על זה לאט יותר?' },
        { en: 'address', he: 'כתובת', t: 'אֶדְרֶס', ex: 'Write your address on the form.', exHe: 'כתוב את הכתובת שלך על הטופס.' }
      ] }
    ]
  };
  root.VOCAB_BANK_EN = BANK;
  if (typeof module !== 'undefined' && module.exports) module.exports = BANK;
})(typeof window !== 'undefined' ? window : globalThis);
