/* LinguaDrive vocabulary bank — Spanish topic packs (loaded by the app and by Node tests) */
(function (root) {
  'use strict';
  var BANK = {
    lang: 'es',
    topics: [
      { id: 'food', he: 'אוכל ושתייה', icon: '🍎', words: [
        { en: 'el pan', he: 'לחם', t: 'אֶל פָּאן', ex: 'Compro pan fresco cada mañana.', exHe: 'אני קונה לחם טרי כל בוקר.' },
        { en: 'la leche', he: 'חלב', t: "לָה לֶצֶ'ה", ex: 'La leche está en la nevera.', exHe: 'החלב נמצא במקרר.' },
        { en: 'el queso', he: 'גבינה', t: 'אֶל קֶסוֹ', ex: 'Este queso es de Francia.', exHe: 'הגבינה הזאת מצרפת.' },
        { en: 'el huevo', he: 'ביצה', t: 'אֶל אוּאֶבוֹ', ex: 'Quiero un huevo para el desayuno.', exHe: 'אני רוצה ביצה לארוחת הבוקר.' },
        { en: 'la manzana', he: 'תפוח', t: 'לָה מַנְסָנָה', ex: 'Como una manzana cada día.', exHe: 'אני אוכל תפוח כל יום.' },
        { en: 'el arroz', he: 'אורז', t: 'אֶל אָרוֹס', ex: 'Cocinamos arroz con verduras.', exHe: 'אנחנו מבשלים אורז עם ירקות.' },
        { en: 'la carne', he: 'בשר', t: 'לָה קַרְנֶה', ex: 'Él no come carne.', exHe: 'הוא לא אוכל בשר.' },
        { en: 'la sopa', he: 'מרק', t: 'לָה סוֹפָּה', ex: 'La sopa está muy caliente.', exHe: 'המרק חם מאוד.' },
        { en: 'el pastel', he: 'עוגה', t: 'אֶל פַּסְטֶל', ex: 'Mi madre hace un pastel rico.', exHe: 'אמא שלי מכינה עוגה טעימה.' },
        { en: 'el zumo', he: 'מיץ', t: 'אֶל סוּמוֹ', ex: 'El zumo de naranja es mi favorito.', exHe: 'מיץ תפוזים הוא האהוב עליי.' },
        { en: 'el café', he: 'קפה', t: 'אֶל קָפֶה', ex: 'Tomo café por la mañana.', exHe: 'אני שותה קפה בבוקר.' },
        { en: 'el té', he: 'תה', t: 'אֶל טֶה', ex: '¿Quieres té con limón?', exHe: 'אתה רוצה תה עם לימון?' },
        { en: 'la mantequilla', he: 'חמאה', t: 'לָה מַנְטֶקִייָה', ex: 'Pon mantequilla en el pan.', exHe: 'שים חמאה על הלחם.' },
        { en: 'el azúcar', he: 'סוכר', t: 'אֶל אָסוּקָר', ex: 'Sin azúcar en mi café, gracias.', exHe: 'בלי סוכר בקפה שלי, תודה.' },
        { en: 'la fruta', he: 'פרי', t: 'לָה פְרוּטָה', ex: 'La fruta fresca es muy sana.', exHe: 'פרי טרי הוא בריא מאוד.' },
        { en: 'las verduras', he: 'ירקות', t: 'לַאס בֶרְדוּרַאס', ex: 'Compramos verduras en el mercado.', exHe: 'אנחנו קונים ירקות בשוק.' },
        { en: 'el desayuno', he: 'ארוחת בוקר', t: 'אֶל דֶסָאיוּנוֹ', ex: 'El desayuno está listo a las ocho.', exHe: 'ארוחת הבוקר מוכנה בשמונה.' },
        { en: 'el almuerzo', he: 'ארוחת צהריים', t: 'אֶל אַלְמוּאֶרְסוֹ', ex: 'El almuerzo es a la una.', exHe: 'ארוחת הצהריים בשעה אחת.' },
        { en: 'la cena', he: 'ארוחת ערב', t: 'לָה סֶנָה', ex: 'La cena es a las siete.', exHe: 'ארוחת הערב בשבע.' },
        { en: 'sabroso', he: 'טעים', t: 'סַבְּרוֹסוֹ', ex: 'Este plato está muy sabroso.', exHe: 'המנה הזאת טעימה מאוד.' }
      ] },
      { id: 'family', he: 'משפחה', icon: '👨‍👩‍👧', words: [
        { en: 'la madre', he: 'אמא', t: 'לָה מַדְרֶה', ex: 'Mi madre vive en Haifa.', exHe: 'אמא שלי גרה בחיפה.' },
        { en: 'el padre', he: 'אבא', t: 'אֶל פַּדְרֶה', ex: 'Su padre es profesor.', exHe: 'אבא שלו מורה.' },
        { en: 'los padres', he: 'הורים', t: 'לוֹס פַּדְרֶס', ex: 'Mis padres viven cerca de mí.', exHe: 'ההורים שלי גרים קרוב אליי.' },
        { en: 'el hermano', he: 'אח', t: 'אֶל אֶרְמָנוֹ', ex: 'Mi hermano es mayor que yo.', exHe: 'אח שלי מבוגר ממני.' },
        { en: 'la hermana', he: 'אחות', t: 'לָה אֶרְמָנָה', ex: 'Su hermana vive en Madrid.', exHe: 'אחותה גרה במדריד.' },
        { en: 'el hijo', he: 'בן', t: 'אֶל אִיחוֹ', ex: 'Su hijo tiene diez años.', exHe: 'הבן שלהם בן עשר.' },
        { en: 'la hija', he: 'בת', t: 'לָה אִיחָה', ex: 'Nuestra hija estudia medicina.', exHe: 'הבת שלנו לומדת רפואה.' },
        { en: 'el marido', he: 'בעל', t: 'אֶל מָרִידוֹ', ex: 'Su marido cocina muy bien.', exHe: 'בעלה מבשל טוב מאוד.' },
        { en: 'la esposa', he: 'אישה (רעיה)', t: 'לָה אֶסְפּוֹסָה', ex: 'Mi esposa habla tres idiomas.', exHe: 'אשתי מדברת שלוש שפות.' },
        { en: 'la abuela', he: 'סבתא', t: 'לָה אָבּוּאֶלָה', ex: 'La abuela cuenta historias bonitas.', exHe: 'סבתא מספרת סיפורים יפים.' },
        { en: 'el abuelo', he: 'סבא', t: 'אֶל אָבּוּאֶלוֹ', ex: 'Mi abuelo tiene noventa años.', exHe: 'סבא שלי בן תשעים.' },
        { en: 'el bebé', he: 'תינוק', t: 'אֶל בֶּבֶּה', ex: 'El bebé duerme todo el día.', exHe: 'התינוק ישן כל היום.' },
        { en: 'el niño', he: 'ילד', t: 'אֶל נִינְיוֹ', ex: 'El niño juega en el jardín.', exHe: 'הילד משחק בגינה.' },
        { en: 'los niños', he: 'ילדים', t: 'לוֹס נִינְיוֹס', ex: 'Los niños van a la escuela.', exHe: 'הילדים הולכים לבית הספר.' },
        { en: 'el tío', he: 'דוד (קרוב משפחה)', t: 'אֶל טִיאוֹ', ex: 'Mi tío tiene una granja grande.', exHe: 'לדוד שלי יש חווה גדולה.' },
        { en: 'la tía', he: 'דודה', t: 'לָה טִיאָה', ex: 'La tía Sara trae regalos.', exHe: 'דודה שרה מביאה מתנות.' },
        { en: 'el primo', he: 'בן דוד', t: 'אֶל פְּרִימוֹ', ex: 'Mi primo trabaja en Tel Aviv.', exHe: 'בן הדוד שלי עובד בתל אביב.' },
        { en: 'casado', he: 'נשוי', t: 'קָסַאדוֹ', ex: 'Está casado y tiene dos hijos.', exHe: 'הוא נשוי ויש לו שני ילדים.' },
        { en: 'juntos', he: 'יחד', t: 'חוּנְטוֹס', ex: 'Cenamos juntos los viernes.', exHe: 'אנחנו אוכלים ארוחת ערב יחד בימי שישי.' },
        { en: 'el amor', he: 'אהבה', t: 'אֶל אָמוֹר', ex: 'El amor de la familia es importante.', exHe: 'אהבת המשפחה חשובה.' }
      ] },
      { id: 'work', he: 'עבודה ומשרד', icon: '💼', words: [
        { en: 'el trabajo', he: 'עבודה (משרה)', t: 'אֶל טְרָבָּחוֹ', ex: 'Ella encontró un trabajo nuevo.', exHe: 'היא מצאה עבודה חדשה.' },
        { en: 'la oficina', he: 'משרד', t: 'לָה אוֹפִיסִינָה', ex: 'La oficina abre a las nueve.', exHe: 'המשרד נפתח בתשע.' },
        { en: 'el jefe', he: 'בוס (מנהל)', t: 'אֶל חֶפֶה', ex: 'Mi jefe es muy simpático.', exHe: 'הבוס שלי נחמד מאוד.' },
        { en: 'la reunión', he: 'פגישה', t: 'לָה רֶאוּנְיוֹן', ex: 'La reunión empieza en diez minutos.', exHe: 'הפגישה מתחילה בעוד עשר דקות.' },
        { en: 'el compañero', he: 'עמית לעבודה', t: 'אֶל קוֹמְפַּנְיֶרוֹ', ex: 'Mi compañero me ayuda mucho.', exHe: 'העמית שלי עוזר לי מאוד.' },
        { en: 'el sueldo', he: 'משכורת', t: 'אֶל סוּאֶלְדוֹ', ex: 'El sueldo llega cada mes.', exHe: 'המשכורת מגיעה כל חודש.' },
        { en: 'el correo', he: 'אימייל (דואר)', t: 'אֶל קוֹרֶאוֹ', ex: 'Leí tu correo esta mañana.', exHe: 'קראתי את האימייל שלך הבוקר.' },
        { en: 'el proyecto', he: 'פרויקט', t: 'אֶל פְּרוֹיֶקְטוֹ', ex: 'El proyecto termina el mes que viene.', exHe: 'הפרויקט מסתיים בחודש הבא.' },
        { en: 'la tarea', he: 'משימה', t: 'לָה טָרֶאָה', ex: 'Esta tarea es fácil para mí.', exHe: 'המשימה הזאת קלה בשבילי.' },
        { en: 'el horario', he: 'לוח זמנים', t: 'אֶל אוֹרַרְיוֹ', ex: 'Mi horario está lleno esta semana.', exHe: 'לוח הזמנים שלי מלא השבוע.' },
        { en: 'la pausa', he: 'הפסקה', t: 'לָה פַּאוּסָה', ex: 'Hacemos una pausa al mediodía.', exHe: 'אנחנו עושים הפסקה בצהריים.' },
        { en: 'el informe', he: 'דוח', t: 'אֶל אִינְפוֹרְמֶה', ex: 'El informe está en tu escritorio.', exHe: 'הדוח נמצא על שולחן הכתיבה שלך.' },
        { en: 'la entrevista', he: 'ראיון', t: 'לָה אֶנְטְרֶבִיסְטָה', ex: 'Tengo una entrevista el domingo.', exHe: 'יש לי ראיון ביום ראשון.' },
        { en: 'contratar', he: 'להעסיק', t: 'קוֹנְטְרָטָאר', ex: 'Quieren contratar a dos personas.', exHe: 'הם רוצים להעסיק שני אנשים.' },
        { en: 'el equipo', he: 'צוות', t: 'אֶל אֶקִיפּוֹ', ex: 'Nuestro equipo funciona muy bien.', exHe: 'הצוות שלנו מתפקד טוב מאוד.' },
        { en: 'el gerente', he: 'מנהל', t: 'אֶל חֶרֶנְטֶה', ex: 'El gerente conoce a cada empleado.', exHe: 'המנהל מכיר כל עובד.' },
        { en: 'firmar', he: 'לחתום', t: 'פִירְמָאר', ex: 'Hay que firmar aquí abajo.', exHe: 'צריך לחתום כאן למטה.' },
        { en: 'imprimir', he: 'להדפיס', t: 'אִימְפְּרִימִיר', ex: '¿Puedes imprimir esta página?', exHe: 'אתה יכול להדפיס את הדף הזה?' },
        { en: 'la empresa', he: 'חברה (עסק)', t: 'לָה אֶמְפְּרֶסָה', ex: 'La empresa tiene cien empleados.', exHe: 'לחברה יש מאה עובדים.' },
        { en: 'ocupado', he: 'עסוק', t: 'אוֹקוּפַּאדוֹ', ex: 'Estoy muy ocupado esta semana.', exHe: 'אני עסוק מאוד השבוע.' }
      ] },
      { id: 'travel', he: 'נסיעות ותחבורה', icon: '✈️', words: [
        { en: 'el aeropuerto', he: 'שדה תעופה', t: 'אֶל אָאֶרוֹפּוּאֶרְטוֹ', ex: 'Llegamos temprano al aeropuerto.', exHe: 'אנחנו מגיעים מוקדם לשדה התעופה.' },
        { en: 'el tren', he: 'רכבת', t: 'אֶל טְרֶן', ex: 'El tren sale a las seis.', exHe: 'הרכבת יוצאת בשש.' },
        { en: 'el autobús', he: 'אוטובוס', t: 'אֶל אָאוּטוֹבּוּס', ex: 'El autobús para cerca de mi casa.', exHe: 'האוטובוס עוצר ליד הבית שלי.' },
        { en: 'el taxi', he: 'מונית', t: 'אֶל טַקְסִי', ex: 'Tomamos un taxi al centro.', exHe: 'אנחנו לוקחים מונית למרכז.' },
        { en: 'la estación', he: 'תחנה', t: 'לָה אֶסְטַסְיוֹן', ex: 'La estación está llena hoy.', exHe: 'התחנה מלאה היום.' },
        { en: 'el mapa', he: 'מפה', t: 'אֶל מַאפָּה', ex: 'Abre el mapa en tu teléfono.', exHe: 'פתח את המפה בטלפון שלך.' },
        { en: 'el hotel', he: 'מלון', t: 'אֶל אוֹטֶל', ex: 'Nuestro hotel está cerca de la playa.', exHe: 'המלון שלנו ליד החוף.' },
        { en: 'el equipaje', he: 'מזוודות (כבודה)', t: 'אֶל אֶקִיפַּחֶה', ex: 'Mi equipaje pesa mucho.', exHe: 'הכבודה שלי שוקלת הרבה.' },
        { en: 'llegar', he: 'להגיע', t: 'יֶגָאר', ex: 'Vamos a llegar por la noche.', exHe: 'אנחנו נגיע בלילה.' },
        { en: 'volver', he: 'לחזור', t: 'בּוֹלְבֶר', ex: 'Queremos volver el domingo.', exHe: 'אנחנו רוצים לחזור ביום ראשון.' },
        { en: 'la carretera', he: 'כביש', t: 'לָה קָרֶטֶרָה', ex: 'Esta carretera va a Jerusalén.', exHe: 'הכביש הזה מוביל לירושלים.' },
        { en: 'el puente', he: 'גשר', t: 'אֶל פּוּאֶנְטֶה', ex: 'El puente viejo cruza el río.', exHe: 'הגשר הישן חוצה את הנהר.' },
        { en: 'el tráfico', he: 'תנועה (פקקים)', t: 'אֶל טְרַאפִיקוֹ', ex: 'Hay mucho tráfico esta mañana.', exHe: 'יש הרבה תנועה הבוקר.' },
        { en: 'el conductor', he: 'נהג', t: 'אֶל קוֹנְדוּקְטוֹר', ex: 'El conductor conoce el camino.', exHe: 'הנהג מכיר את הדרך.' },
        { en: 'el pasajero', he: 'נוסע', t: 'אֶל פָּסָחֶרוֹ', ex: 'Cada pasajero necesita un asiento.', exHe: 'כל נוסע צריך מושב.' },
        { en: 'el andén', he: 'רציף', t: 'אֶל אַנְדֶן', ex: 'El tren espera en el andén dos.', exHe: 'הרכבת ממתינה ברציף שתיים.' },
        { en: 'el turista', he: 'תייר', t: 'אֶל טוּרִיסְטָה', ex: 'El turista hace muchas fotos.', exHe: 'התייר מצלם הרבה תמונות.' },
        { en: 'la dirección', he: 'כיוון (כתובת)', t: 'לָה דִירֶקְסְיוֹן', ex: '¿En qué dirección está el museo?', exHe: 'באיזה כיוון נמצא המוזיאון?' },
        { en: 'el metro', he: 'רכבת תחתית', t: 'אֶל מֶטְרוֹ', ex: 'El metro es rápido y barato.', exHe: 'המטרו מהיר וזול.' },
        { en: 'la parada', he: 'תחנת עצירה', t: 'לָה פָּרַאדָה', ex: 'La parada está en la esquina.', exHe: 'התחנה נמצאת בפינה.' }
      ] },
      { id: 'shopping', he: 'קניות וכסף', icon: '🛒', words: [
        { en: 'el dinero', he: 'כסף', t: 'אֶל דִינֶרוֹ', ex: 'Necesito dinero para el mercado.', exHe: 'אני צריך כסף לשוק.' },
        { en: 'el precio', he: 'מחיר', t: 'אֶל פְּרֶסְיוֹ', ex: 'El precio es demasiado alto.', exHe: 'המחיר גבוה מדי.' },
        { en: 'barato', he: 'זול', t: 'בָּרַאטוֹ', ex: 'Este restaurante es bueno y barato.', exHe: 'המסעדה הזאת טובה וזולה.' },
        { en: 'caro', he: 'יקר', t: 'קַארוֹ', ex: 'Este reloj es muy caro.', exHe: 'השעון הזה יקר מאוד.' },
        { en: 'la rebaja', he: 'מבצע (הוזלה)', t: 'לָה רֶבָּחָה', ex: 'Hay una gran rebaja hoy.', exHe: 'יש מבצע גדול היום.' },
        { en: 'el efectivo', he: 'מזומן', t: 'אֶל אֶפֶקְטִיבוֹ', ex: 'Pago en efectivo, no con tarjeta.', exHe: 'אני משלם במזומן, לא בכרטיס.' },
        { en: 'la tarjeta', he: 'כרטיס (אשראי)', t: 'לָה טַרְחֶטָה', ex: '¿Puedo pagar con tarjeta?', exHe: 'אפשר לשלם בכרטיס?' },
        { en: 'la cartera', he: 'ארנק', t: 'לָה קַרְטֶרָה', ex: 'Mi cartera está en el bolso.', exHe: 'הארנק שלי בתיק.' },
        { en: 'el recibo', he: 'קבלה', t: 'אֶל רֶסִיבּוֹ', ex: 'Guarda el recibo, por si acaso.', exHe: 'שמור את הקבלה, ליתר ביטחון.' },
        { en: 'el descuento', he: 'הנחה', t: 'אֶל דֶסְקוּאֶנְטוֹ', ex: 'Hoy hay un descuento del diez por ciento.', exHe: 'היום יש הנחה של עשרה אחוזים.' },
        { en: 'el mercado', he: 'שוק', t: 'אֶל מֶרְקַאדוֹ', ex: 'El mercado abre los viernes.', exHe: 'השוק פתוח בימי שישי.' },
        { en: 'el supermercado', he: 'סופרמרקט', t: 'אֶל סוּפֶּרְמֶרְקַאדוֹ', ex: 'El supermercado cierra a las diez.', exHe: 'הסופרמרקט נסגר בעשר.' },
        { en: 'el cliente', he: 'לקוח', t: 'אֶל קְלִיאֶנְטֶה', ex: 'El cliente siempre tiene razón.', exHe: 'הלקוח תמיד צודק.' },
        { en: 'pagar', he: 'לשלם', t: 'פָּגָאר', ex: '¿Dónde puedo pagar esta camisa?', exHe: 'איפה אפשר לשלם על החולצה הזאת?' },
        { en: 'costar', he: 'לעלות (במחיר)', t: 'קוֹסְטָאר', ex: '¿Cuánto puede costar este bolso?', exHe: 'כמה יכול לעלות התיק הזה?' },
        { en: 'gastar', he: 'להוציא (כסף)', t: 'גַסְטָאר', ex: 'No quiero gastar todo mi dinero.', exHe: 'אני לא רוצה להוציא את כל הכסף שלי.' },
        { en: 'ahorrar', he: 'לחסוך', t: 'אָאוֹרָאר', ex: 'Queremos ahorrar dinero cada mes.', exHe: 'אנחנו רוצים לחסוך כסף כל חודש.' },
        { en: 'la cesta', he: 'סל', t: 'לָה סֶסְטָה', ex: 'Pon el pan en la cesta.', exHe: 'שים את הלחם בסל.' },
        { en: 'el cajero', he: 'קופאי', t: 'אֶל קָחֶרוֹ', ex: 'El cajero me da el cambio.', exHe: 'הקופאי נותן לי את העודף.' },
        { en: 'el cambio', he: 'עודף', t: 'אֶל קַמְבְּיוֹ', ex: 'Aquí tiene el cambio, señor.', exHe: 'הנה העודף שלך, אדוני.' }
      ] },
      { id: 'health', he: 'בריאות וגוף', icon: '🩺', words: [
        { en: 'la enfermera', he: 'אחות (רפואית)', t: 'לָה אֶנְפֶרְמֶרָה', ex: 'La enfermera es muy amable.', exHe: 'האחות מאוד אדיבה.' },
        { en: 'el hospital', he: 'בית חולים', t: 'אֶל אוֹסְפִּיטָל', ex: 'El hospital está cerca del centro.', exHe: 'בית החולים נמצא ליד המרכז.' },
        { en: 'el dentista', he: 'רופא שיניים', t: 'אֶל דֶנְטִיסְטָה', ex: 'Voy al dentista dos veces al año.', exHe: 'אני הולך לרופא שיניים פעמיים בשנה.' },
        { en: 'el diente', he: 'שן', t: 'אֶל דְיֶנְטֶה', ex: 'Me duele un diente desde ayer.', exHe: 'כואבת לי שן מאתמול.' },
        { en: 'el dolor', he: 'כאב', t: 'אֶל דוֹלוֹר', ex: 'El dolor ya casi pasó.', exHe: 'הכאב כמעט עבר.' },
        { en: 'la tos', he: 'שיעול', t: 'לָה טוֹס', ex: 'La tos empezó hace dos días.', exHe: 'השיעול התחיל לפני יומיים.' },
        { en: 'el resfriado', he: 'הצטננות', t: 'אֶל רֶסְפְרִיאַדוֹ', ex: 'Tengo un resfriado fuerte.', exHe: 'יש לי הצטננות חזקה.' },
        { en: 'la gripe', he: 'שפעת', t: 'לָה גְרִיפֶּה', ex: 'Mucha gente tiene la gripe ahora.', exHe: 'הרבה אנשים חולים בשפעת עכשיו.' },
        { en: 'la medicina', he: 'תרופה', t: 'לָה מֶדִיסִינָה', ex: 'Toma la medicina después de comer.', exHe: 'קח את התרופה אחרי האוכל.' },
        { en: 'la cita', he: 'תור (לרופא)', t: 'לָה סִיטָה', ex: 'Mi cita es a las cuatro.', exHe: 'התור שלי בשעה ארבע.' },
        { en: 'enfermo', he: 'חולה', t: 'אֶנְפֶרְמוֹ', ex: 'Está enfermo desde el lunes.', exHe: 'הוא חולה מיום שני.' },
        { en: 'la mano', he: 'יד', t: 'לָה מָנוֹ', ex: 'Me lavo las manos antes de comer.', exHe: 'אני שוטף ידיים לפני האוכל.' },
        { en: 'la pierna', he: 'רגל', t: 'לָה פְּיֶרְנָה', ex: 'Me duele la pierna derecha.', exHe: 'כואבת לי הרגל הימנית.' },
        { en: 'el ojo', he: 'עין', t: 'אֶל אוֹחוֹ', ex: 'Mi ojo derecho está rojo.', exHe: 'העין הימנית שלי אדומה.' },
        { en: 'la oreja', he: 'אוזן', t: 'לָה אוֹרֶחָה', ex: 'Me duele la oreja por la noche.', exHe: 'כואבת לי האוזן בלילה.' },
        { en: 'el corazón', he: 'לב', t: 'אֶל קוֹרָסוֹן', ex: 'Un corazón fuerte necesita ejercicio.', exHe: 'לב חזק צריך פעילות גופנית.' },
        { en: 'el estómago', he: 'בטן', t: 'אֶל אֶסְטוֹמָגוֹ', ex: 'Mi estómago está lleno.', exHe: 'הבטן שלי מלאה.' },
        { en: 'la garganta', he: 'גרון', t: 'לָה גַרְגַנְטָה', ex: 'Me arde la garganta un poco.', exHe: 'הגרון שלי צורב קצת.' },
        { en: 'respirar', he: 'לנשום', t: 'רֶסְפִּירָאר', ex: 'Respira despacio y tranquilo.', exHe: 'נשום לאט ובנחת.' },
        { en: 'fuerte', he: 'חזק', t: 'פוּאֶרְטֶה', ex: 'Ella es fuerte y sana.', exHe: 'היא חזקה ובריאה.' }
      ] },
      { id: 'home', he: 'בית ודירה', icon: '🏠', words: [
        { en: 'el piso', he: 'דירה', t: 'אֶל פִּיסוֹ', ex: 'Nuestro piso tiene tres habitaciones.', exHe: 'בדירה שלנו יש שלושה חדרים.' },
        { en: 'el dormitorio', he: 'חדר שינה', t: 'אֶל דוֹרְמִיטוֹרְיוֹ', ex: 'El dormitorio tiene un armario grande.', exHe: 'בחדר השינה יש ארון גדול.' },
        { en: 'el baño', he: 'חדר אמבטיה', t: 'אֶל בַּאנְיוֹ', ex: 'El baño está al final del pasillo.', exHe: 'חדר האמבטיה בסוף המסדרון.' },
        { en: 'el salón', he: 'סלון', t: 'אֶל סָלוֹן', ex: 'Vemos la tele en el salón.', exHe: 'אנחנו רואים טלוויזיה בסלון.' },
        { en: 'la cama', he: 'מיטה', t: 'לָה קָמָה', ex: 'La cama es muy cómoda.', exHe: 'המיטה מאוד נוחה.' },
        { en: 'el sofá', he: 'ספה', t: 'אֶל סוֹפָה', ex: 'El gato duerme en el sofá.', exHe: 'החתול ישן על הספה.' },
        { en: 'la ducha', he: 'מקלחת', t: "לָה דוּצָ'ה", ex: 'Tomo una ducha cada noche.', exHe: 'אני מתקלח כל ערב.' },
        { en: 'el suelo', he: 'רצפה', t: 'אֶל סוּאֶלוֹ', ex: 'El suelo está limpio ahora.', exHe: 'הרצפה נקייה עכשיו.' },
        { en: 'la pared', he: 'קיר', t: 'לָה פָּרֶד', ex: 'Hay un cuadro en la pared.', exHe: 'יש תמונה על הקיר.' },
        { en: 'el techo', he: 'תקרה', t: "אֶל טֶצ'וֹ", ex: 'El techo necesita una reparación.', exHe: 'התקרה צריכה תיקון.' },
        { en: 'el jardín', he: 'גינה', t: 'אֶל חַרְדִין', ex: 'El jardín está lleno de flores.', exHe: 'הגינה מלאה בפרחים.' },
        { en: 'el balcón', he: 'מרפסת', t: 'אֶל בַּלְקוֹן', ex: 'Tomamos café en el balcón.', exHe: 'אנחנו שותים קפה במרפסת.' },
        { en: 'la escalera', he: 'מדרגות', t: 'לָה אֶסְקָלֶרָה', ex: 'La escalera va al segundo piso.', exHe: 'המדרגות מובילות לקומה השנייה.' },
        { en: 'el ascensor', he: 'מעלית', t: 'אֶל אַסֶנְסוֹר', ex: 'El ascensor no funciona hoy.', exHe: 'המעלית לא עובדת היום.' },
        { en: 'la ventana', he: 'חלון', t: 'לָה בֶנְטָנָה', ex: 'Abre la ventana, por favor.', exHe: 'פתח את החלון, בבקשה.' },
        { en: 'la lámpara', he: 'מנורה', t: 'לָה לַאמְפָּרָה', ex: 'Enciende la lámpara, está oscuro.', exHe: 'הדלק את המנורה, חשוך.' },
        { en: 'el espejo', he: 'מראה', t: 'אֶל אֶסְפֶּחוֹ', ex: 'Hay un espejo en la entrada.', exHe: 'יש מראה בכניסה.' },
        { en: 'la nevera', he: 'מקרר', t: 'לָה נֶבֶרָה', ex: 'La nevera está casi vacía.', exHe: 'המקרר כמעט ריק.' },
        { en: 'el vecino', he: 'שכן', t: 'אֶל בֶסִינוֹ', ex: 'Nuestro vecino es muy tranquilo.', exHe: 'השכן שלנו מאוד שקט.' },
        { en: 'alquilar', he: 'לשכור', t: 'אַלְקִילָאר', ex: 'Queremos alquilar un piso pequeño.', exHe: 'אנחנו רוצים לשכור דירה קטנה.' }
      ] },
      { id: 'weather', he: 'טבע ומזג אוויר', icon: '🌦️', words: [
        { en: 'el sol', he: 'שמש', t: 'אֶל סוֹל', ex: 'El sol está fuerte hoy.', exHe: 'השמש חזקה היום.' },
        { en: 'la lluvia', he: 'גשם', t: 'לָה יוּבְיָה', ex: 'La lluvia paró hace una hora.', exHe: 'הגשם פסק לפני שעה.' },
        { en: 'la nieve', he: 'שלג', t: 'לָה נְיֶבֶה', ex: 'La nieve es rara en Tel Aviv.', exHe: 'שלג הוא דבר נדיר בתל אביב.' },
        { en: 'el viento', he: 'רוח', t: 'אֶל בְּיֶנְטוֹ', ex: 'El viento está frío esta noche.', exHe: 'הרוח קרה הלילה.' },
        { en: 'la nube', he: 'ענן', t: 'לָה נוּבֶּה', ex: 'Hay una nube pequeña en el cielo.', exHe: 'יש ענן קטן בשמיים.' },
        { en: 'la tormenta', he: 'סערה', t: 'לָה טוֹרְמֶנְטָה', ex: 'Viene una tormenta grande mañana.', exHe: 'סערה גדולה מגיעה מחר.' },
        { en: 'el calor', he: 'חום (מזג אוויר)', t: 'אֶל קָלוֹר', ex: 'En agosto hace mucho calor.', exHe: 'באוגוסט חם מאוד.' },
        { en: 'el frío', he: 'קור', t: 'אֶל פְרִיאוֹ', ex: 'El frío llega en diciembre.', exHe: 'הקור מגיע בדצמבר.' },
        { en: 'soleado', he: 'שמשי', t: 'סוֹלֶאַדוֹ', ex: 'Está soleado casi todo el año.', exHe: 'שמשי כמעט כל השנה.' },
        { en: 'nublado', he: 'מעונן', t: 'נוּבְּלַאדוֹ', ex: 'El día está gris y nublado.', exHe: 'היום אפור ומעונן.' },
        { en: 'el paraguas', he: 'מטרייה', t: 'אֶל פָּרַגוּאַס', ex: 'Lleva un paraguas contigo.', exHe: 'קח איתך מטרייה.' },
        { en: 'la temperatura', he: 'טמפרטורה', t: 'לָה טֶמְפֶּרָטוּרָה', ex: 'La temperatura baja por la noche.', exHe: 'הטמפרטורה יורדת בלילה.' },
        { en: 'el cielo', he: 'שמיים', t: 'אֶל סְיֶלוֹ', ex: 'El cielo está azul y claro.', exHe: 'השמיים כחולים ובהירים.' },
        { en: 'el mar', he: 'ים', t: 'אֶל מַאר', ex: 'El mar está tranquilo esta mañana.', exHe: 'הים רגוע הבוקר.' },
        { en: 'la montaña', he: 'הר', t: 'לָה מוֹנְטַנְיָה', ex: 'La montaña está blanca en invierno.', exHe: 'ההר לבן בחורף.' },
        { en: 'el río', he: 'נהר', t: 'אֶל רִיאוֹ', ex: 'El río pasa por la ciudad.', exHe: 'הנהר עובר דרך העיר.' },
        { en: 'el árbol', he: 'עץ', t: 'אֶל אַרְבּוֹל', ex: 'El árbol viejo da buena sombra.', exHe: 'העץ הזקן נותן צל טוב.' },
        { en: 'la flor', he: 'פרח', t: 'לָה פְלוֹר', ex: 'Esta flor abre en primavera.', exHe: 'הפרח הזה נפתח באביב.' },
        { en: 'la playa', he: 'חוף', t: 'לָה פְּלַאיָה', ex: 'La playa está vacía en invierno.', exHe: 'החוף ריק בחורף.' },
        { en: 'el bosque', he: 'יער', t: 'אֶל בּוֹסְקֶה', ex: 'Paseamos por el bosque el sábado.', exHe: 'אנחנו מטיילים ביער בשבת.' }
      ] },
      { id: 'feelings', he: 'רגשות', icon: '💚', words: [
        { en: 'feliz', he: 'מאושר', t: 'פֶלִיס', ex: 'Estoy feliz con mi nueva vida.', exHe: 'אני מאושר עם החיים החדשים שלי.' },
        { en: 'triste', he: 'עצוב', t: 'טְרִיסְטֶה', ex: 'La película me puso triste.', exHe: 'הסרט העציב אותי.' },
        { en: 'enfadado', he: 'כועס', t: 'אֶנְפָדַאדוֹ', ex: 'No estés enfadado conmigo.', exHe: 'אל תכעס עליי.' },
        { en: 'asustado', he: 'מפוחד', t: 'אָסוּסְטַאדוֹ', ex: 'El niño está asustado por el perro.', exHe: 'הילד מפוחד מהכלב.' },
        { en: 'emocionado', he: 'נרגש', t: 'אֶמוֹסְיוֹנַאדוֹ', ex: 'Estamos emocionados por la boda.', exHe: 'אנחנו נרגשים לקראת החתונה.' },
        { en: 'aburrido', he: 'משועמם', t: 'אָבּוּרִידוֹ', ex: 'Los alumnos parecen aburridos hoy.', exHe: 'התלמידים נראים משועממים היום.' },
        { en: 'sorprendido', he: 'מופתע', t: 'סוֹרְפְּרֶנְדִידוֹ', ex: 'Estoy sorprendido por el regalo.', exHe: 'אני מופתע מהמתנה.' },
        { en: 'orgulloso', he: 'גאה', t: 'אוֹרְגוּיוֹסוֹ', ex: 'Estoy orgulloso de mi hija.', exHe: 'אני גאה בבת שלי.' },
        { en: 'solo', he: 'בודד (לבד)', t: 'סוֹלוֹ', ex: 'Se siente solo en la ciudad grande.', exHe: 'הוא מרגיש בודד בעיר הגדולה.' },
        { en: 'nervioso', he: 'לחוץ (עצבני)', t: 'נֶרְבְיוֹסוֹ', ex: 'Estoy nervioso antes del examen.', exHe: 'אני לחוץ לפני המבחן.' },
        { en: 'tranquilo', he: 'רגוע', t: 'טְרַנְקִילוֹ', ex: 'Quédate tranquilo y habla claro.', exHe: 'הישאר רגוע ודבר ברור.' },
        { en: 'contento', he: 'מרוצה', t: 'קוֹנְטֶנְטוֹ', ex: 'Estoy contento con mi trabajo.', exHe: 'אני מרוצה מהעבודה שלי.' },
        { en: 'preocupado', he: 'מודאג', t: 'פְּרֶאוֹקוּפַּאדוֹ', ex: 'Está preocupado por las noticias.', exHe: 'הוא מודאג מהחדשות.' },
        { en: 'cómodo', he: 'נוח', t: 'קוֹמוֹדוֹ', ex: 'Este sillón es muy cómodo.', exHe: 'הכורסה הזאת מאוד נוחה.' },
        { en: 'la esperanza', he: 'תקווה', t: 'לָה אֶסְפֶּרַנְסָה', ex: 'La esperanza es lo último que se pierde.', exHe: 'התקווה היא הדבר האחרון שאובד.' },
        { en: 'la sonrisa', he: 'חיוך', t: 'לָה סוֹנְרִיסָה', ex: 'Su sonrisa alegra a todos.', exHe: 'החיוך שלה משמח את כולם.' },
        { en: 'llorar', he: 'לבכות', t: 'יוֹרָאר', ex: 'Los bebés lloran cuando tienen hambre.', exHe: 'תינוקות בוכים כשהם רעבים.' },
        { en: 'reír', he: 'לצחוק', t: 'רֶאִיר', ex: 'Nos gusta reír juntos en casa.', exHe: 'אנחנו אוהבים לצחוק יחד בבית.' },
        { en: 'sentir', he: 'להרגיש', t: 'סֶנְטִיר', ex: 'Puedo sentir el calor del sol.', exHe: 'אני יכול להרגיש את חום השמש.' },
        { en: 'el miedo', he: 'פחד', t: 'אֶל מְיֶדוֹ', ex: 'El miedo desaparece con el tiempo.', exHe: 'הפחד נעלם עם הזמן.' }
      ] },
      { id: 'time', he: 'זמן ולוח שנה', icon: '🕒', words: [
        { en: 'la mañana', he: 'בוקר', t: 'לָה מַנְיָאנָה', ex: 'La mañana es mi momento favorito.', exHe: 'הבוקר הוא הרגע האהוב עליי.' },
        { en: 'la tarde', he: 'אחר הצהריים', t: 'לָה טַרְדֶה', ex: 'Por la tarde tomamos café.', exHe: 'אחר הצהריים אנחנו שותים קפה.' },
        { en: 'la noche', he: 'לילה', t: "לָה נוֹצֶ'ה", ex: 'La noche está tranquila aquí.', exHe: 'הלילה שקט כאן.' },
        { en: 'el mediodía', he: 'צהריים', t: 'אֶל מֶדְיוֹדִיאָה', ex: 'La tienda cierra al mediodía el viernes.', exHe: 'החנות נסגרת בצהריים ביום שישי.' },
        { en: 'la medianoche', he: 'חצות', t: "לָה מֶדְיָאנוֹצֶ'ה", ex: 'La fiesta terminó a medianoche.', exHe: 'המסיבה הסתיימה בחצות.' },
        { en: 'la hora', he: 'שעה', t: 'לָה אוֹרָה', ex: 'La clase dura una hora.', exHe: 'השיעור נמשך שעה אחת.' },
        { en: 'el minuto', he: 'דקה', t: 'אֶל מִינוּטוֹ', ex: 'Espera un minuto, ya voy.', exHe: 'חכה דקה, אני כבר בא.' },
        { en: 'la semana', he: 'שבוע', t: 'לָה סֶמָנָה', ex: 'Esta semana tenemos una fiesta.', exHe: 'השבוע יש לנו מסיבה.' },
        { en: 'el mes', he: 'חודש', t: 'אֶל מֶס', ex: 'Este mes tiene treinta días.', exHe: 'בחודש הזה יש שלושים יום.' },
        { en: 'el año', he: 'שנה', t: 'אֶל אַנְיוֹ', ex: 'El año pasa muy rápido.', exHe: 'השנה עוברת מהר מאוד.' },
        { en: 'la fecha', he: 'תאריך', t: "לָה פֶצָ'ה", ex: '¿Cuál es la fecha de hoy?', exHe: 'מה התאריך היום?' },
        { en: 'el calendario', he: 'לוח שנה', t: 'אֶל קָלֶנְדַרְיוֹ', ex: 'La reunión está en el calendario.', exHe: 'הפגישה רשומה בלוח השנה.' },
        { en: 'temprano', he: 'מוקדם', t: 'טֶמְפְּרַאנוֹ', ex: 'Me despierto temprano cada día.', exHe: 'אני מתעורר מוקדם כל יום.' },
        { en: 'el cumpleaños', he: 'יום הולדת', t: 'אֶל קוּמְפְּלֶאַנְיוֹס', ex: 'Su cumpleaños es en marzo.', exHe: 'יום ההולדת שלה במרץ.' },
        { en: 'la fiesta', he: 'מסיבה (חג)', t: 'לָה פְיֶסְטָה', ex: 'La fiesta empieza a las nueve.', exHe: 'המסיבה מתחילה בתשע.' },
        { en: 'la primavera', he: 'אביב', t: 'לָה פְּרִימָבֶרָה', ex: 'En primavera todo se pone verde.', exHe: 'באביב הכול נהיה ירוק.' },
        { en: 'el verano', he: 'קיץ', t: 'אֶל בֶרַאנוֹ', ex: 'El verano aquí es largo y caluroso.', exHe: 'הקיץ כאן ארוך וחם.' },
        { en: 'el invierno', he: 'חורף', t: 'אֶל אִינְבְיֶרְנוֹ', ex: 'En invierno oscurece temprano.', exHe: 'בחורף מחשיך מוקדם.' },
        { en: 'el otoño', he: 'סתיו', t: 'אֶל אוֹטוֹנְיוֹ', ex: 'En otoño caen las hojas.', exHe: 'בסתיו העלים נושרים.' },
        { en: 'el día', he: 'יום', t: 'אֶל דִיאָה', ex: 'Hoy es un día especial.', exHe: 'היום הוא יום מיוחד.' }
      ] },
      { id: 'clothes', he: 'בגדים', icon: '👕', words: [
        { en: 'la camisa', he: 'חולצה', t: 'לָה קָמִיסָה', ex: 'La camisa azul te queda bien.', exHe: 'החולצה הכחולה מתאימה לך.' },
        { en: 'los pantalones', he: 'מכנסיים', t: 'לוֹס פַּנְטָלוֹנֶס', ex: 'Estos pantalones son demasiado largos.', exHe: 'המכנסיים האלה ארוכים מדי.' },
        { en: 'el vestido', he: 'שמלה', t: 'אֶל בֶּסְטִידוֹ', ex: 'Ella lleva un vestido rojo.', exHe: 'היא לובשת שמלה אדומה.' },
        { en: 'la falda', he: 'חצאית', t: 'לָה פַלְדָה', ex: 'La falda va bien con los zapatos.', exHe: 'החצאית הולכת טוב עם הנעליים.' },
        { en: 'el abrigo', he: 'מעיל', t: 'אֶל אָבְּרִיגוֹ', ex: 'Lleva un abrigo, hace frío fuera.', exHe: 'קח מעיל, קר בחוץ.' },
        { en: 'la chaqueta', he: "ז'קט", t: "לָה צָ'קֶטָה", ex: 'La chaqueta tiene bolsillos grandes.', exHe: "לז'קט יש כיסים גדולים." },
        { en: 'los zapatos', he: 'נעליים', t: 'לוֹס סָפַּאטוֹס', ex: 'Mis zapatos nuevos son cómodos.', exHe: 'הנעליים החדשות שלי נוחות.' },
        { en: 'los calcetines', he: 'גרביים', t: 'לוֹס קַלְסֶטִינֶס', ex: 'Necesito calcetines limpios para mañana.', exHe: 'אני צריך גרביים נקיים למחר.' },
        { en: 'el sombrero', he: 'כובע', t: 'אֶל סוֹמְבְּרֶרוֹ', ex: 'Ponte un sombrero al sol.', exHe: 'חבוש כובע בשמש.' },
        { en: 'la bufanda', he: 'צעיף', t: 'לָה בּוּפַנְדָה', ex: 'La bufanda me protege del frío.', exHe: 'הצעיף מגן עליי מהקור.' },
        { en: 'los guantes', he: 'כפפות', t: 'לוֹס גוּאַנְטֶס', ex: 'Ponte los guantes cuando nieva.', exHe: 'לבש כפפות כשיורד שלג.' },
        { en: 'el jersey', he: 'סוודר', t: 'אֶל חֶרְסֵיי', ex: 'Este jersey es de lana.', exHe: 'הסוודר הזה עשוי צמר.' },
        { en: 'el cinturón', he: 'חגורה', t: 'אֶל סִינְטוּרוֹן', ex: 'Necesito un cinturón para estos pantalones.', exHe: 'אני צריך חגורה למכנסיים האלה.' },
        { en: 'la corbata', he: 'עניבה', t: 'לָה קוֹרְבָּטָה', ex: 'Lleva corbata a las reuniones.', exHe: 'הוא עונב עניבה לפגישות.' },
        { en: 'el bolsillo', he: 'כיס', t: 'אֶל בּוֹלְסִייוֹ', ex: 'Las llaves están en mi bolsillo.', exHe: 'המפתחות בכיס שלי.' },
        { en: 'la talla', he: 'מידה', t: 'לָה טַאיָה', ex: '¿Tiene una talla más grande?', exHe: 'יש לך מידה גדולה יותר?' },
        { en: 'llevar', he: 'ללבוש (לשאת)', t: 'יֶבָאר', ex: '¿Qué vas a llevar esta noche?', exHe: 'מה תלבש הערב?' },
        { en: 'probarse', he: 'למדוד (בגד)', t: 'פְּרוֹבַּארְסֶה', ex: '¿Puedo probarme este vestido?', exHe: 'אפשר למדוד את השמלה הזאת?' },
        { en: 'la moda', he: 'אופנה', t: 'לָה מוֹדָה', ex: 'Le encanta la moda italiana.', exHe: 'היא אוהבת אופנה איטלקית.' },
        { en: 'la ropa', he: 'בגדים', t: 'לָה רוֹפָּה', ex: 'La ropa está en el armario.', exHe: 'הבגדים נמצאים בארון.' }
      ] },
      { id: 'sport', he: 'ספורט ופנאי', icon: '⚽', words: [
        { en: 'el juego', he: 'משחק', t: 'אֶל חוּאֶגוֹ', ex: 'El juego empieza a las ocho.', exHe: 'המשחק מתחיל בשמונה.' },
        { en: 'la pelota', he: 'כדור (משחק)', t: 'לָה פֶּלוֹטָה', ex: 'Tírame la pelota, por favor.', exHe: 'זרוק אליי את הכדור, בבקשה.' },
        { en: 'el fútbol', he: 'כדורגל', t: 'אֶל פוּטְבּוֹל', ex: 'Jugamos al fútbol los sábados.', exHe: 'אנחנו משחקים כדורגל בשבתות.' },
        { en: 'el baloncesto', he: 'כדורסל', t: 'אֶל בָּלוֹנְסֶסְטוֹ', ex: 'A mi hijo le encanta el baloncesto.', exHe: 'הבן שלי אוהב כדורסל.' },
        { en: 'la natación', he: 'שחייה', t: 'לָה נָטַסְיוֹן', ex: 'La natación es un ejercicio excelente.', exHe: 'שחייה היא פעילות גופנית מצוינת.' },
        { en: 'correr', he: 'לרוץ', t: 'קוֹרֶר', ex: 'Me gusta correr por la playa.', exHe: 'אני אוהב לרוץ על החוף.' },
        { en: 'el gimnasio', he: 'חדר כושר', t: 'אֶל חִימְנַסְיוֹ', ex: 'Voy al gimnasio dos veces por semana.', exHe: 'אני הולך לחדר כושר פעמיים בשבוע.' },
        { en: 'el ejercicio', he: 'התעמלות', t: 'אֶל אֶחֶרְסִיסְיוֹ', ex: 'Un poco de ejercicio cada día ayuda.', exHe: 'קצת התעמלות כל יום עוזרת.' },
        { en: 'el entrenador', he: 'מאמן', t: 'אֶל אֶנְטְרֶנָדוֹר', ex: 'El entrenador está orgulloso del equipo.', exHe: 'המאמן גאה בקבוצה.' },
        { en: 'el jugador', he: 'שחקן', t: 'אֶל חוּגָדוֹר', ex: 'Es el mejor jugador del equipo.', exHe: 'הוא השחקן הכי טוב בקבוצה.' },
        { en: 'ganar', he: 'לנצח', t: 'גָנָאר', ex: 'Esperamos ganar el partido esta noche.', exHe: 'אנחנו מקווים לנצח במשחק הערב.' },
        { en: 'perder', he: 'להפסיד', t: 'פֶּרְדֶר', ex: 'A nadie le gusta perder.', exHe: 'אף אחד לא אוהב להפסיד.' },
        { en: 'el gol', he: 'שער (גול)', t: 'אֶל גוֹל', ex: 'El primer gol llegó muy pronto.', exHe: 'השער הראשון הגיע מוקדם מאוד.' },
        { en: 'la carrera', he: 'מרוץ', t: 'לָה קָרֶרָה', ex: 'La carrera empieza en el parque.', exHe: 'המרוץ מתחיל בפארק.' },
        { en: 'la bicicleta', he: 'אופניים', t: 'לָה בִּיסִיקְלֶטָה', ex: 'Voy en bicicleta al mar.', exHe: 'אני רוכב על אופניים לים.' },
        { en: 'el partido', he: 'משחק (תחרות)', t: 'אֶל פַּרְטִידוֹ', ex: 'El partido terminó sin goles.', exHe: 'המשחק הסתיים ללא שערים.' },
        { en: 'el parque', he: 'פארק', t: 'אֶל פַּארְקֶה', ex: 'El parque está lleno los sábados.', exHe: 'הפארק מלא בשבתות.' },
        { en: 'bailar', he: 'לרקוד', t: 'בַּיילָאר', ex: 'Bailamos todos los viernes.', exHe: 'אנחנו רוקדים כל יום שישי.' },
        { en: 'nadar', he: 'לשחות', t: 'נָדָאר', ex: 'Aprendo a nadar en la piscina.', exHe: 'אני לומד לשחות בבריכה.' },
        { en: 'divertido', he: 'כיפי (מהנה)', t: 'דִיבֶרְטִידוֹ', ex: 'El picnic fue muy divertido.', exHe: 'הפיקניק היה מאוד מהנה.' }
      ] },
      { id: 'tech', he: 'טכנולוגיה ומסכים', icon: '📱', words: [
        { en: 'el teléfono', he: 'טלפון', t: 'אֶל טֶלֶפוֹנוֹ', ex: 'Mi teléfono suena todo el día.', exHe: 'הטלפון שלי מצלצל כל היום.' },
        { en: 'el ordenador', he: 'מחשב', t: 'אֶל אוֹרְדֶנָדוֹר', ex: 'El ordenador va lento hoy.', exHe: 'המחשב איטי היום.' },
        { en: 'la pantalla', he: 'מסך', t: 'לָה פַּנְטַאיָה', ex: 'La pantalla brilla demasiado.', exHe: 'המסך בוהק מדי.' },
        { en: 'internet', he: 'אינטרנט', t: 'אִינְטֶרְנֶט', ex: 'Internet no funciona otra vez.', exHe: 'האינטרנט לא עובד שוב.' },
        { en: 'la página web', he: 'אתר אינטרנט', t: 'לָה פַּאחִינָה וֶובּ', ex: 'Esta página web tiene buenas recetas.', exHe: 'באתר הזה יש מתכונים טובים.' },
        { en: 'la contraseña', he: 'סיסמה', t: 'לָה קוֹנְטְרָסֶנְיָה', ex: 'Cambia tu contraseña cada año.', exHe: 'החלף את הסיסמה שלך כל שנה.' },
        { en: 'el mensaje', he: 'הודעה', t: 'אֶל מֶנְסַאחֶה', ex: 'Mándame un mensaje más tarde.', exHe: 'שלח לי הודעה מאוחר יותר.' },
        { en: 'la cámara', he: 'מצלמה', t: 'לָה קַאמָרָה', ex: 'La cámara hace fotos preciosas.', exHe: 'המצלמה מצלמת תמונות מקסימות.' },
        { en: 'la foto', he: 'תמונה', t: 'לָה פוֹטוֹ', ex: 'Esta foto es de nuestra boda.', exHe: 'התמונה הזאת מהחתונה שלנו.' },
        { en: 'el vídeo', he: 'סרטון', t: 'אֶל בִּידֵאוֹ', ex: 'El vídeo dura dos minutos.', exHe: 'הסרטון נמשך שתי דקות.' },
        { en: 'la aplicación', he: 'אפליקציה', t: 'לָה אַפְּלִיקַסְיוֹן', ex: 'Esta aplicación es gratis y fácil.', exHe: 'האפליקציה הזאת חינמית וקלה.' },
        { en: 'la batería', he: 'סוללה', t: 'לָה בָּטֶרִיאָה', ex: 'La batería dura todo el día.', exHe: 'הסוללה מחזיקה כל היום.' },
        { en: 'el cargador', he: 'מטען', t: 'אֶל קַרְגָדוֹר', ex: 'Olvidé el cargador en casa.', exHe: 'שכחתי את המטען בבית.' },
        { en: 'el wifi', he: 'וויי-פיי', t: 'אֶל וִויפִי', ex: 'El wifi es gratis en el hotel.', exHe: 'הוויי-פיי חינם במלון.' },
        { en: 'el teclado', he: 'מקלדת', t: 'אֶל טֶקְלַאדוֹ', ex: 'El teclado necesita pilas nuevas.', exHe: 'המקלדת צריכה סוללות חדשות.' },
        { en: 'el ratón', he: 'עכבר (מחשב)', t: 'אֶל רָטוֹן', ex: 'Haz clic con el ratón.', exHe: 'לחץ עם העכבר.' },
        { en: 'el archivo', he: 'קובץ', t: "אֶל אַרְצִ'יבוֹ", ex: 'Guarda el archivo antes de cerrar.', exHe: 'שמור את הקובץ לפני הסגירה.' },
        { en: 'descargar', he: 'להוריד (קובץ)', t: 'דֶסְקַרְגָאר', ex: 'Puedes descargar el formulario aquí.', exHe: 'אתה יכול להוריד את הטופס כאן.' },
        { en: 'el enlace', he: 'קישור', t: 'אֶל אֶנְלַאסֶה', ex: 'El enlace está en el mensaje.', exHe: 'הקישור נמצא בהודעה.' },
        { en: 'en línea', he: 'מקוון', t: 'אֶן לִינֵאָה', ex: 'La clase es en línea los martes.', exHe: 'השיעור מקוון בימי שלישי.' }
      ] },
      { id: 'restaurant', he: 'במסעדה', icon: '🍽️', words: [
        { en: 'el camarero', he: 'מלצר', t: 'אֶל קָמָרֶרוֹ', ex: 'El camarero trae el pan.', exHe: 'המלצר מביא את הלחם.' },
        { en: 'reservar', he: 'להזמין מקום', t: 'רֶסֶרְבָאר', ex: 'Quiero reservar para dos personas.', exHe: 'אני רוצה להזמין מקום לשניים.' },
        { en: 'el plato', he: 'מנה (צלחת)', t: 'אֶל פְּלַאטוֹ', ex: 'Este plato viene con arroz.', exHe: 'המנה הזאת מגיעה עם אורז.' },
        { en: 'el postre', he: 'קינוח', t: 'אֶל פּוֹסְטְרֶה', ex: 'El postre de chocolate es maravilloso.', exHe: 'קינוח השוקולד נפלא.' },
        { en: 'el primer plato', he: 'מנה ראשונה', t: 'אֶל פְּרִימֶר פְּלַאטוֹ', ex: 'De primer plato quiero la sopa.', exHe: 'כמנה ראשונה אני רוצה את המרק.' },
        { en: 'la copa', he: 'כוס (יין)', t: 'לָה קוֹפָּה', ex: 'Una copa de vino tinto, por favor.', exHe: 'כוס יין אדום, בבקשה.' },
        { en: 'la botella', he: 'בקבוק', t: 'לָה בּוֹטֵיָה', ex: 'Una botella de agua fría, por favor.', exHe: 'בקבוק מים קרים, בבקשה.' },
        { en: 'el tenedor', he: 'מזלג', t: 'אֶל טֶנֶדוֹר', ex: 'Mi tenedor se cayó al suelo.', exHe: 'המזלג שלי נפל על הרצפה.' },
        { en: 'el cuchillo', he: 'סכין', t: "אֶל קוּצִ'ייוֹ", ex: 'Este cuchillo no corta bien.', exHe: 'הסכין הזאת לא חותכת טוב.' },
        { en: 'la cuchara', he: 'כף', t: "לָה קוּצָ'רָה", ex: 'Necesito una cuchara para la sopa.', exHe: 'אני צריך כף למרק.' },
        { en: 'la servilleta', he: 'מפית', t: 'לָה סֶרְבִייֶטָה', ex: '¿Me trae una servilleta, por favor?', exHe: 'אפשר לקבל מפית, בבקשה?' },
        { en: 'la propina', he: 'טיפ (תשר)', t: 'לָה פְּרוֹפִּינָה', ex: 'Siempre dejamos una buena propina.', exHe: 'אנחנו תמיד משאירים טיפ נדיב.' },
        { en: 'el vino', he: 'יין', t: 'אֶל בִּינוֹ', ex: 'Este vino es de la Rioja.', exHe: 'היין הזה מריוחה.' },
        { en: 'la cerveza', he: 'בירה', t: 'לָה סֶרְבֶסָה', ex: 'Una cerveza fría en un día caluroso.', exHe: 'בירה קרה ביום חם.' },
        { en: 'el helado', he: 'גלידה', t: 'אֶל אֶלַאדוֹ', ex: 'Los niños quieren helado de fresa.', exHe: 'הילדים רוצים גלידת תות.' },
        { en: 'dulce', he: 'מתוק', t: 'דוּלְסֶה', ex: 'El pastel es demasiado dulce para mí.', exHe: 'העוגה מתוקה מדי בשבילי.' },
        { en: 'el menú', he: 'תפריט', t: 'אֶל מֶנוּ', ex: '¿Puedo ver el menú del día?', exHe: 'אפשר לראות את תפריט היום?' },
        { en: 'pedir', he: 'להזמין (אוכל)', t: 'פֶּדִיר', ex: 'Vamos a pedir dos cafés.', exHe: 'אנחנו נזמין שני קפה.' },
        { en: 'fresco', he: 'טרי', t: 'פְרֶסְקוֹ', ex: 'El pan de aquí está siempre fresco.', exHe: 'הלחם כאן תמיד טרי.' },
        { en: 'salado', he: 'מלוח', t: 'סָלַאדוֹ', ex: 'La sopa está un poco salada.', exHe: 'המרק קצת מלוח.' }
      ] },
      { id: 'help', he: 'חירום ועזרה', icon: '🆘', words: [
        { en: 'la emergencia', he: 'מקרה חירום', t: 'לָה אֶמֶרְחֶנְסְיָה', ex: 'En una emergencia, llama a este número.', exHe: 'במקרה חירום, התקשר למספר הזה.' },
        { en: 'la policía', he: 'משטרה', t: 'לָה פּוֹלִיסִיאָה', ex: 'La policía está en camino.', exHe: 'המשטרה בדרך.' },
        { en: 'el fuego', he: 'אש (שריפה)', t: 'אֶל פוּאֶגוֹ', ex: '¡Hay fuego en la cocina!', exHe: 'יש אש במטבח!' },
        { en: 'la ambulancia', he: 'אמבולנס', t: 'לָה אַמְבּוּלַנְסְיָה', ex: 'La ambulancia llegó en cinco minutos.', exHe: 'האמבולנס הגיע תוך חמש דקות.' },
        { en: 'el peligro', he: 'סכנה', t: 'אֶל פֶּלִיגְרוֹ', ex: '¡Peligro! El agua es profunda.', exHe: 'סכנה! המים עמוקים.' },
        { en: 'peligroso', he: 'מסוכן', t: 'פֶּלִיגְרוֹסוֹ', ex: 'Este camino es peligroso de noche.', exHe: 'הדרך הזאת מסוכנת בלילה.' },
        { en: 'cuidado', he: 'זהירות', t: 'קוּאִידַאדוֹ', ex: '¡Cuidado! El suelo está mojado.', exHe: 'זהירות! הרצפה רטובה.' },
        { en: 'el accidente', he: 'תאונה', t: 'אֶל אַקְסִידֶנְטֶה', ex: 'Hubo un accidente en la carretera.', exHe: 'הייתה תאונה בכביש.' },
        { en: 'llamar', he: 'להתקשר', t: 'יָמָאר', ex: 'Voy a llamar a la policía.', exHe: 'אני הולך להתקשר למשטרה.' },
        { en: 'ayudar', he: 'לעזור', t: 'אָיוּדָאר', ex: '¿Me puedes ayudar con esto?', exHe: 'אתה יכול לעזור לי עם זה?' },
        { en: 'la salida', he: 'יציאה', t: 'לָה סָלִידָה', ex: 'La salida está a la izquierda.', exHe: 'היציאה נמצאת בצד שמאל.' },
        { en: 'la entrada', he: 'כניסה', t: 'לָה אֶנְטְרַאדָה', ex: 'La entrada está detrás del edificio.', exHe: 'הכניסה מאחורי הבניין.' },
        { en: 'empujar', he: 'לדחוף', t: 'אֶמְפּוּחָאר', ex: 'Hay que empujar la puerta.', exHe: 'צריך לדחוף את הדלת.' },
        { en: 'tirar', he: 'למשוך (בדלת)', t: 'טִירָאר', ex: 'Tira de la puerta, no empujes.', exHe: 'משוך את הדלת, אל תדחף.' },
        { en: 'abierto', he: 'פתוח', t: 'אָבְּיֶרְטוֹ', ex: 'La clínica está abierta hasta el mediodía.', exHe: 'המרפאה פתוחה עד הצהריים.' },
        { en: 'cerrado', he: 'סגור', t: 'סֶרַאדוֹ', ex: 'El banco está cerrado el sábado.', exHe: 'הבנק סגור בשבת.' },
        { en: 'esperar', he: 'לחכות', t: 'אֶסְפֶּרָאר', ex: 'Hay que esperar la luz verde.', exHe: 'צריך לחכות לאור הירוק.' },
        { en: 'urgente', he: 'דחוף', t: 'אוּרְחֶנְטֶה', ex: 'Es un caso urgente, ven rápido.', exHe: 'זה מקרה דחוף, בוא מהר.' },
        { en: 'el bombero', he: 'כבאי', t: 'אֶל בּוֹמְבֶּרוֹ', ex: 'El bombero apaga el fuego.', exHe: 'הכבאי מכבה את האש.' },
        { en: 'rápido', he: 'מהיר (מהר)', t: 'רַאפִּידוֹ', ex: 'El metro es muy rápido.', exHe: 'המטרו מהיר מאוד.' }
      ] }
    ]
  };
  root.VOCAB_BANK_ES = BANK;
  if (typeof module !== 'undefined' && module.exports) module.exports = BANK;
})(typeof window !== 'undefined' ? window : globalThis);
